import 'package:flutter/widgets.dart';

import 'app_state.dart';

String tx(BuildContext context, String hu) {
  final language = AppScope.of(context).language;
  if (language == AppLanguage.hungarian) return hu;
  return _translations[language]?[hu] ?? hu;
}

String txBmiCategory(BuildContext context, String category) =>
    switch (category) {
      'Sovány' => tx(context, 'Sovány'),
      'Normál súly' => tx(context, 'Normál súly'),
      'Túlsúlyos' => tx(context, 'Túlsúlyos'),
      'Obezitás' => tx(context, 'Obezitás'),
      _ => category,
    };

const _translations = {
  AppLanguage.english: {
    'Lista': 'List',
    'Kalória': 'Calories',
    'Profil': 'Profile',
    'Főételek': 'Main dishes',
    'Köretek': 'Sides',
    'Receptek': 'Recipes',
    'Recept': 'Recipe',
    'Kedvencek': 'Favorites',
    'Keresés receptek között': 'Search recipes',
    'Mind': 'All',
    'Normál receptek': 'Normal',
    'Vegán': 'Vegan',
    'Nincs találat.': 'No results.',
    'Reggeli': 'Breakfast',
    'Ebéd': 'Lunch',
    'Vacsora': 'Dinner',
    'Nasi': 'Snack',
    'Étrendek': 'Meal plans',
    'Étrend': 'Meal plan',
    'étkezés': 'meals',
    'Napi bontás': 'Daily breakdown',
    'Hamarosan': 'Soon',
    'Válassz étrend típust': 'Choose a meal plan type',
    'A konkrét napi étrendeket a következő lépésben töltjük fel.':
        'We will add the concrete daily meal plans in the next step.',
    'Válassz egy típust, majd nézd meg a hozzá tartozó napi étrendeket.':
        'Choose a type, then view its daily meal plans.',
    '1500 kcal étrendek': '1500 kcal meal plans',
    'Étrend típusok': 'Meal plan types',
    'Magas fehérje': 'High protein',
    'Edzéshez és jobb teltségérzethez': 'For training and better satiety',
    'Gluténmentes': 'Gluten-free',
    'Glutént tartalmazó alapanyagok nélkül':
        'Without ingredients containing gluten',
    'Vegetáriánus': 'Vegetarian',
    'Húsmentes napi étrend': 'Meat-free daily plan',
    'Gyors': 'Quick',
    'Rövid elkészítési idejű ételekkel': 'With meals that are quick to prepare',
    'Pénztárcabarát': 'Budget-friendly',
    'Egyszerűbb, olcsóbb alapanyagokkal': 'With simpler, cheaper ingredients',
    'Meal prep alapú': 'Meal Prep based',
    'Előre dobozolható napi menü': 'Daily menu you can prep ahead',
    'Erős nap': 'Strong Day',
    'Fitt nap': 'Fit Day',
    'Könnyű nap': 'Light Day',
    'Tiszta nap': 'Clean Day',
    'Zöld nap': 'Green Day',
    'Friss nap': 'Fresh Day',
    'Tempós nap': 'Quick Day',
    'Sietős nap': 'Fast Day',
    'Okos nap': 'Smart Day',
    'Egyszerű nap': 'Simple Day',
    'Dobozolós nap': 'Prep Box Day',
    'Előre főzős nap': 'Cook-Ahead Day',
    'Protein zabkása bogyós gyümölccsel': 'Protein oatmeal with berries',
    'Tojásos avokádós pirítós': 'Egg avocado toast',
    'Görög joghurtos granola pohár': 'Greek yogurt granola cup',
    'Túrós zabpalacsinta': 'Cottage cheese oat pancakes',
    'Pulykás tojásos wrap': 'Turkey egg wrap',
    'Almás fahéjas overnight oats': 'Apple cinnamon overnight oats',
    'Lazacos krémsajtos bagel': 'Salmon cream cheese bagel',
    'Zöldséges omlett': 'Vegetable omelette',
    'Banános mogyoróvajas smoothie': 'Banana peanut butter smoothie',
    'Sós cottage cheese tál': 'Savory cottage cheese bowl',
    'Csirkés rizses fit bowl': 'Chicken rice fit bowl',
    'Pulykás bolognai tészta': 'Turkey bolognese pasta',
    'Lazacos burgonyás ebéd': 'Salmon potato lunch',
    'Marhahúsos bulgur serpenyő': 'Beef bulgur skillet',
    'Tofus zöldséges noodle box': 'Tofu vegetable noodle box',
    'Csicseriborsó curry rizzsel': 'Chickpea curry with rice',
    'Sertésszűz kuszkusszal': 'Pork tenderloin with couscous',
    'Lencsés feta saláta': 'Lentil feta salad',
    'Csirkés pita tál': 'Chicken pita bowl',
    'Tonhalas kukoricás tésztasaláta': 'Tuna corn pasta salad',
    'Könnyű csirkés saláta': 'Light chicken salad',
    'Tojásos zöldséges rizs': 'Egg vegetable rice',
    'Pulykagolyók cukkinispagettivel': 'Turkey meatballs with zucchini noodles',
    'Sült hal zöldségágyon': 'Baked fish on vegetables',
    'Cottage cheese zöldségtál': 'Cottage cheese vegetable plate',
    'Garnélás quinoa bowl': 'Shrimp quinoa bowl',
    'Könnyű babos chili': 'Light bean chili',
    'Sonkás sajtos omlett': 'Ham and cheese omelette',
    'Töltött paprika light módra': 'Light stuffed peppers',
    'Görög csirkés tányér': 'Greek chicken plate',
    'Protein joghurt pohár': 'Protein yogurt cup',
    'Almaszeletek mogyoróvajjal': 'Apple slices with peanut butter',
    'Rizsszelet cottage cheese-zel': 'Rice cakes with cottage cheese',
    'Banános kakaós falatok': 'Banana cocoa bites',
    'Hummuszos zöldségdoboz': 'Hummus vegetable box',
    'Fehérjés puding': 'Protein pudding',
    'Főtt tojás avokádóval': 'Boiled eggs with avocado',
    'Tonhalas ropogós falatok': 'Crunchy tuna bites',
    'Túrós bogyós tál': 'Cottage cheese berry bowl',
    'Mini csirkés wrap': 'Mini chicken wrap',
    'Csirkés rizses fit bowl kisebb adagban':
        'Chicken rice fit bowl, smaller portion',
    'Pulykás bolognai tészta light adagban':
        'Turkey bolognese pasta, light portion',
    'Fehérjés puding fél adag gyümölccsel': 'Half protein pudding with fruit',
    'Görög joghurtos granola pohár gluténmentes granolával':
        'Greek yogurt granola cup with gluten-free granola',
    'Overnight oats előre bekészítve': 'Overnight oats prepped ahead',
    'Túrós zabpalacsinta előre sütve':
        'Cottage cheese oat pancakes cooked ahead',
    'Főétel': 'Main dish',
    'Köret': 'Side',
    'Új étel': 'New food',
    'Új étel hozzáadása': 'Add new food',
    'Étel neve': 'Food name',
    'Nyers g': 'Raw g',
    'Kész g': 'Cooked g',
    'Kimért g': 'Serving g',
    'Nyers adag': 'Raw amount',
    'Kész súly': 'Cooked weight',
    'Kész étel': 'Cooked meal',
    'Kész étel súlya': 'Cooked meal weight',
    'Kimért adag': 'Served amount',
    'Nyers egyenérték': 'Raw equivalent',
    'Bevásárlás+': 'Shopping+',
    'Meal Prep+': 'Meal Prep+',
    'Új meal prep terv': 'New Meal Prep plan',
    'Elmentett meal prep tervek': 'Saved Meal Prep Plans',
    'Még nincs elmentett meal prep terved.':
        'You do not have a saved Meal Prep plan yet.',
    'Először ments el egy ételt a meal prep tervezéshez.':
        'Save a food first to plan Meal Prep.',
    'Ingyenes módban 1 meal prep tervet menthetsz. A további tervekhez Pro szükséges.':
        'In free mode, you can save 1 Meal Prep plan. More plans require Pro.',
    'Válassz ételt és adagold dobozokra':
        'Choose a food and split it into boxes',
    'Válassz főételt, köretet és adagold dobozokra':
        'Choose a main dish, side, and split into boxes',
    'Meal prep terv szerkesztése': 'Edit Meal Prep plan',
    'Teljes mennyiség elosztása': 'Split total amount',
    'Fix adagméret': 'Fixed portion size',
    'Az app a mentett kész mennyiséget osztja el az adagok között.':
        'The app splits the saved cooked amount between portions.',
    'Te adod meg, hány gramm kerüljön egy adagba.':
        'You set how many grams go into each portion.',
    'Terv neve': 'Plan name',
    'Mentett étel': 'Saved food',
    'Köret hozzáadása': 'Add side',
    'Nincs köret': 'No side',
    'Nincs mentett étel': 'No saved food',
    'Adagok': 'Portions',
    'g / adag': 'g / portion',
    'Főétel g / adag': 'Main g / portion',
    'Köret g / adag': 'Side g / portion',
    'Megjegyzés': 'Note',
    'Szükséges kész étel': 'Cooked food needed',
    'Szükséges nyers alapanyag': 'Raw ingredients needed',
    'Szükséges kész főétel': 'Cooked main needed',
    'Szükséges nyers főétel': 'Raw main needed',
    'Főétel adag / doboz': 'Main portion / box',
    'Főétel recept szorzó': 'Main recipe multiplier',
    'Szükséges kész köret': 'Cooked side needed',
    'Szükséges nyers köret': 'Raw side needed',
    'Köret adag / doboz': 'Side portion / box',
    'Köret recept szorzó': 'Side recipe multiplier',
    'Köret nyers egyenértéke': 'Side raw equivalent',
    'Recept szorzó': 'Recipe multiplier',
    'Egy adag nyers egyenértéke': 'Raw equivalent per portion',
    'Dobozok': 'Boxes',
    'adag': 'portion',
    'Szerkesztés': 'Edit',
    'Új bevásárlólista': 'New shopping list',
    'Bevásárlólista szerkesztése': 'Edit shopping list',
    'Bevásárlólista törlése': 'Delete shopping list',
    'Biztosan törlöd ezt a bevásárlólistát?':
        'Are you sure you want to delete this shopping list?',
    'Elmentett listák': 'Saved lists',
    'Még nincs elmentett bevásárlólistád.':
        'You do not have a saved shopping list yet.',
    'Nevezd el és add hozzá a tételeket': 'Name it and add the items',
    'Lista neve': 'List name',
    'Pl. Hétvégi főzés': 'E.g. Weekend cooking',
    'Hozzávalók': 'Ingredients',
    'Hozzávaló': 'Ingredient',
    'Elkészítés': 'Preparation',
    'Allergének': 'Allergens',
    'Adagok száma': 'Number of servings',
    'Összes kalória': 'Total calories',
    'perc': 'min',
    'Bevásárláshoz adás': 'Add to shopping',
    'Bevásárlólista mentése': 'Save shopping list',
    'Új lista neve': 'New list name',
    'Mentés új listaként': 'Save as new list',
    'Meglévő listához adás': 'Add to existing list',
    'tétel': 'items',
    'Tétel hozzáadása': 'Add item',
    'Hozzáadva': 'Added',
    'Jegyzet': 'Note',
    'Írj receptet, tippet vagy emlékeztetőt...':
        'Write a recipe, tip, or reminder...',
    'Mégse': 'Cancel',
    'Mentés': 'Save',
    'Mentve': 'Saved',
    'Mealr Pro': 'Mealr Pro',
    'Korlátlan mentés és extra funkciók': 'Unlimited saving and extra features',
    'Több mentés, bevásárlólisták, súlykövetés extrák':
        'More saves, shopping lists, weight tracking extras',
    'Részletek': 'Details',
    'Próbáld ki ingyen 7 napig': 'Try free for 7 days',
    'Éves csomag −50% kedvezménnyel': 'Yearly plan with −50% discount',
    'Kihagyás': 'Skip',
    'Az összeget csak a 7. nap után vonjuk le · Bármikor lemondható':
        'You are charged only after day 7 · Cancel anytime',
    'FUNKCIÓ': 'FEATURE',
    'Ingyenes': 'Free',
    'Pro': 'Pro',
    'Ingyenes alapok': 'Free basics',
    'Amit már most használhatsz': 'What you can use right now',
    'Pro-val feloldható extrák': 'Extras unlocked with Pro',
    'Rendszeres használathoz': 'For regular use',
    'Főétel mentés': 'Main dish saving',
    'Köret mentés': 'Side saving',
    'Étel megosztás': 'Food sharing',
    'Bevásárlás+ listák': 'Shopping+ lists',
    'Meal Prep tervező': 'Meal Prep planner',
    'Heti táplálkozási pillanatkép': 'Weekly nutrition snapshot',
    'Korlátlan étel és meal prep mentés': 'Unlimited food and Meal Prep saving',
    'Korlátlan': 'Unlimited',
    '30/60 napos súlydiagram és statisztika':
        '30/60-day weight chart and statistics',
    'Súlykövetés diagram': 'Weight tracking chart',
    'Súlynapló szerkesztés': 'Weight log editing',
    'Fogyás statisztika': 'Weight loss statistics',
    'Témák (6 db)': 'Themes (6)',
    'Havi előfizetés': 'Monthly subscription',
    'Éves előfizetés': 'Yearly subscription',
    'Bármikor lemondható': 'Cancel anytime',
    '= 1.00€/hó · legjobb ár': '= 1.00€/mo · best value',
    '/hó': '/mo',
    '/év': '/yr',
    'db': 'pcs',
    'Nyers súly kalkulátor': 'Raw weight calculator',
    'Értem, kezdjük el! →': 'Got it, let’s start! →',
    'Tovább': 'Next',
    'MIÉRT HASZNOS?': 'WHY IS IT USEFUL?',
    'A főtt étel súlya változik, a kalória nem.':
        'Cooked food weight changes, calories do not.',
    'A Mealr azért kell, hogy ne kelljen fejben számolgatnod, amikor főzés után kevesebb vagy több lesz az étel tömege. Beírod a nyers, kész és kimért súlyt, az app pedig megmondja, mennyi nyers alapanyagnak felel meg az adag.':
        'Mealr saves you from mental math when food weighs less or more after cooking. Enter raw, cooked, and served weight, and the app tells you the raw ingredient equivalent of your portion.',
    'Így pontosabban tudod vezetni a kalóriákat, és a meal prep adagolás sem lesz találgatás.':
        'This makes calorie tracking more accurate, and Meal Prep portions stop being guesswork.',
    'mérd le főzés előtt az alapanyagokat, például csirke + rizs + zöldség összesen 950 g.':
        'weigh the ingredients before cooking, for example chicken + rice + vegetables totaling 950 g.',
    'főzés után mérd le az egész elkészült ételt, például 760 g.':
        'after cooking, weigh the finished meal, for example 760 g.',
    'ha a dobozodba 250 g kerül, a Mealr kiszámolja, hogy ez kb. 313 g nyers alapanyagnak felel meg.':
        'if 250 g goes into your container, Mealr calculates that it equals about 313 g of raw ingredients.',
    'Köret külön vezetve': 'Tracking sides separately',
    'Ha csak rizst, bulgurt vagy tésztát főzöl köretnek, ugyanígy működik: nyers rizs 300 g, kész rizs 820 g, kimért adag 180 g. Az app megadja a nyers rizs egyenértékét.':
        'If you cook only rice, bulgur, or pasta as a side, it works the same way: raw rice 300 g, cooked rice 820 g, served portion 180 g. The app gives the raw rice equivalent.',
    'Külön köretnél is ugyanígy működik: ha a nyers alapanyag főzés közben vizet vesz fel, a kész tömeg több lehet, de ettől nem lesz több benne a kalória. A Mealr ilyenkor is a nyers egyenértéket számolja ki.':
        'It works the same for separate sides: if a raw ingredient absorbs water while cooking, the cooked weight can be higher, but that does not add calories. Mealr still calculates the raw equivalent.',
    'MINDEN EGYBEN': 'ALL IN ONE',
    'Nem csak mérlegelés: egy app a kajás rutinodhoz.':
        'Not just weighing: one app for your food routine.',
    'A Mealr egy helyre gyűjti a főzéshez, adagoláshoz és célkövetéshez hasznos eszközöket, hogy ne több app között kelljen ugrálnod.':
        'Mealr brings cooking, portioning, and goal-tracking tools into one place so you do not have to jump between apps.',
    'Kalória kalkulátor': 'Calorie calculator',
    'BMI': 'BMI',
    'Bevásárlás lista': 'Shopping list',
    'Súly követés': 'Weight tracking',
    'Meal preppelés': 'Meal Prepping',
    'MI A PROBLÉMA?': 'WHAT IS THE PROBLEM?',
    'Főzés során az étel ': 'During cooking, food ',
    'veszít a tömegéből': 'loses weight',
    ' – de nem a kalóriájából. Ha a kész súlyt írod be a kalóriaszámlálóba, ':
        ' - but not calories. If you enter cooked weight into your calorie tracker, ',
    'téves értéket kapsz.': 'you get an incorrect value.',
    'Főzés során az étel tömege ': 'During cooking, food weight ',
    'csökkenhet vagy növekedhet': 'can decrease or increase',
    ', de ettől ': ', but this ',
    'nem változik a kalóriája.': 'does not change its calories.',
    'HOGYAN SEGÍT A MEALR?': 'HOW DOES MEALR HELP?',
    'a száraz, nyers hozzávalók össztömege főzés előtt':
        'the total dry, raw ingredient weight before cooking',
    'az étel össztömege főzés vagy sütés után':
        'the total meal weight after cooking or baking',
    'amit a tányérra teszel → megkapod a ':
        'what you put on your plate → you get the ',
    'nyers egyenértéket': 'raw equivalent',
    'A mentett ételekhez bármikor visszatérhetsz – naponta csak a kimért adagot kell módosítani.':
        'You can return to saved foods anytime - daily you only adjust the served amount.',
    'Kalória\nkalkulátor': 'Calorie\ncalculator',
    'Számold ki a napi szintentartó kalóriádat életkor, súly, magasság és aktivitás alapján.':
        'Calculate your daily maintenance calories from age, weight, height, and activity.',
    'BMI\nkalkulátor': 'BMI\ncalculator',
    'Ellenőrizd az ideális testsúlyod és kövesd nyomon a változásokat. Mentve a profilodba.':
        'Check your ideal weight and track changes. Saved to your profile.',
    'Hogyan működik?': 'How does it work?',
    ', de ': ', but ',
    'nem a kalóriájából.': 'not its calories.',
    ' Ha a kész súlyt írod be a kalóriaszámlálóba, téves értéket kapsz.':
        ' If you enter cooked weight into your calorie tracker, you get an incorrect value.',
    'Add össze a száraz, nyers hozzávalókat főzés ':
        'Add up the dry, raw ingredients ',
    'előtt': 'before cooking',
    ' – ezt mérd le és írd be.': ' - measure this and enter it.',
    'Ha megfőzted vagy megsütötted az ételt, mérd le az ':
        'After cooking or baking the meal, measure the ',
    'össztömeget': 'total weight',
    ' és írd be ide.': ' and enter it here.',
    'Ha enni szeretnél, mérd le a tányérodra kerülő adagot és írd be – megkapod a ':
        'When you want to eat, measure the portion on your plate and enter it - you get the ',
    'nyers egyenértéket.': 'raw equivalent.',
    'Képlet: ': 'Formula: ',
    'nyers ÷ kész × kimért =\nnyers egyenérték\n':
        'raw ÷ cooked × served =\nraw equivalent\n',
    '→ Ezt a számot írd be a kalóriaszámlálódba\n(pl. MyFitnessPal, Cronometer stb.)':
        '→ Enter this number into your calorie tracker\n(e.g. MyFitnessPal, Cronometer, etc.)',
    'Bezárás': 'Close',
    'TESTTÖMEG INDEX (BMI)': 'BODY MASS INDEX (BMI)',
    'Sovány': 'Underweight',
    'Normál': 'Normal',
    'Normál súly': 'Normal weight',
    'Túlsúly': 'Overweight',
    'Túlsúlyos': 'Overweight',
    'Obezitás': 'Obesity',
    'Ideális testsúly': 'Ideal weight',
    'A BMI csak tájékoztató. Nem veszi figyelembe az izomtömeget. Orvosi diagnózisra nem alkalmas.':
        'BMI is for guidance only. It does not account for muscle mass and is not a medical diagnosis.',
    'A BMI 18.5 alatt sovány tartomány.': 'BMI below 18.5 is underweight.',
    'A normál BMI tartomány 18.5–24.9. Egészséges testsúlyon vagy!':
        'Normal BMI range is 18.5-24.9. You are in a healthy range!',
    'A BMI 25–29.9 között túlsúly.': 'BMI between 25-29.9 is overweight.',
    'A BMI 30 felett obezitás tartomány.': 'BMI above 30 is obesity range.',
    'Nem': 'Gender',
    'Férfi': 'Male',
    'Nő': 'Female',
    'Súly (kg)': 'Weight (kg)',
    'Magasság (cm)': 'Height (cm)',
    'Mentve a profilba.': 'Saved to profile.',
    'Mentve a profilba · legközelebb automatikusan kitöltve':
        'Saved to profile · prefilled next time',
    'NAPI SZINTENTARTÓ KALÓRIA': 'DAILY MAINTENANCE CALORIES',
    'kcal / nap': 'kcal / day',
    'Fogyáshoz': 'For fat loss',
    'Tömegnövelés': 'For gaining',
    'Életkor': 'Age',
    'Napi aktivitás': 'Daily activity',
    'Ülő életmód': 'Sedentary',
    'Enyhén aktív (heti 1–3x)': 'Lightly active (1-3x/week)',
    'Közepesen aktív (heti 3–5x)': 'Moderately active (3-5x/week)',
    'Erősen aktív (heti 6–7x)': 'Very active (6-7x/week)',
    'Extrém aktív': 'Extremely active',
    'HOGYAN HASZNÁLD?': 'HOW TO USE IT?',
    'Fogyáshoz: ': 'For fat loss: ',
    'vonj le 300–500 kcal-t. Napi 500 kcal deficit ≈ heti 0,5 kg fogyás.\n\n':
        'subtract 300-500 kcal. A daily 500 kcal deficit is about 0.5 kg loss per week.\n\n',
    'Tömegnöveléshez: ': 'For gaining: ',
    'adj 150–300 kcal-t a szintentartóhoz.\n\n':
        'add 150-300 kcal to maintenance.\n\n',
    'Iránymutató – 2–4 hétig kövesd, majd a tényleges változás alapján igazítsd.':
        'Use as a guide for 2-4 weeks, then adjust based on actual progress.',
    'Mentés profilba · a Kalória cél frissítése':
        'Save to profile · update calorie goal',
    'Személyes adatok': 'Personal data',
    'Súly': 'Weight',
    'Magasság': 'Height',
    'Kalória cél': 'Calorie goal',
    'Kalkulátorból beállítva': 'Set from calculator',
    'Súlykövetés': 'Weight tracking',
    'Súly progresszió': 'Weight progress',
    'Adj hozzá legalább két súlyt a diagramhoz.':
        'Add at least two weights to show the chart.',
    'nap': 'days',
    'Hozzáadás': 'Add',
    'Rögzített súlyok': 'Recorded weights',
    'További rögzítések': 'Show more records',
    'Kevesebb mutatása': 'Show less',
    'Progresszió törlése': 'Delete progress',
    'Biztosan törlöd az összes rögzített súlyt?':
        'Are you sure you want to delete all recorded weights?',
    'Törlés': 'Delete',
    'Súly szerkesztése': 'Edit weight',
    'Nincs változás a kezdő súlyhoz képest':
        'No change compared with starting weight',
    'Eddigi fogyás': 'Weight lost so far',
    'Eddigi változás': 'Total change so far',
    'Pro statisztika': 'Pro statistics',
    'Összes': 'Total',
    '7 nap': '7 days',
    '30 nap': '30 days',
    'Heti átlag': 'Weekly average',
    'hét': 'week',
    'Trend': 'Trend',
    'Legalacsonyabb': 'Lowest',
    'Csökkenő': 'Decreasing',
    'Stagnál': 'Stable',
    'Emelkedő': 'Increasing',
    'Beállítások': 'Settings',
    'Nyelv, téma, mód és verzió': 'Language, theme, mode, and version',
    'Téma': 'Theme',
    'Nyelv': 'Language',
    'Sötét mód': 'Dark mode',
    'Előfizetés': 'Subscription',
    'Pro mód teszt': 'Pro mode test',
    'Verzió 1.0.0': 'Version 1.0.0',
    'Aktív előfizetés · ': 'Active subscription · ',
    ' Pro extrák lezárva': ' · Pro extras locked',
    'Nincs aktív előfizetés': 'No active subscription',
    'Lejár: ': 'Expires: ',
    'Alapértelmezett: English': 'Default: English',
    'Téma választása': 'Choose theme',
  },
  AppLanguage.german: {
    'Lista': 'Liste',
    'Kalória': 'Kalorien',
    'Profil': 'Profil',
    'Főételek': 'Hauptgerichte',
    'Köretek': 'Beilagen',
    'Receptek': 'Rezepte',
    'Recept': 'Rezept',
    'Kedvencek': 'Favoriten',
    'Reggeli': 'Frühstück',
    'Ebéd': 'Mittagessen',
    'Vacsora': 'Abendessen',
    'Nasi': 'Snack',
    'Étrendek': 'Ernährungspläne',
    'Étrend': 'Ernährungsplan',
    'étkezés': 'Mahlzeiten',
    'Napi bontás': 'Tagesübersicht',
    'Hamarosan': 'Bald',
    'Válassz étrend típust': 'Wähle einen Ernährungsplantyp',
    'A konkrét napi étrendeket a következő lépésben töltjük fel.':
        'Die konkreten Tagespläne fügen wir im nächsten Schritt hinzu.',
    'Válassz egy típust, majd nézd meg a hozzá tartozó napi étrendeket.':
        'Wähle einen Typ und sieh dir die passenden Tagespläne an.',
    '1500 kcal étrendek': '1500-kcal-Ernährungspläne',
    'Étrend típusok': 'Ernährungsplantypen',
    'Magas fehérje': 'Proteinreich',
    'Edzéshez és jobb teltségérzethez': 'Für Training und bessere Sättigung',
    'Gluténmentes': 'Glutenfrei',
    'Glutént tartalmazó alapanyagok nélkül': 'Ohne glutenhaltige Zutaten',
    'Vegetáriánus': 'Vegetarisch',
    'Húsmentes napi étrend': 'Fleischfreier Tagesplan',
    'Gyors': 'Schnell',
    'Rövid elkészítési idejű ételekkel': 'Mit schnell zubereiteten Mahlzeiten',
    'Pénztárcabarát': 'Budgetfreundlich',
    'Egyszerűbb, olcsóbb alapanyagokkal':
        'Mit einfacheren, günstigeren Zutaten',
    'Meal prep alapú': 'Meal-Prep-basiert',
    'Előre dobozolható napi menü': 'Tagesmenü zum Vorbereiten',
    'Erős nap': 'Starker Tag',
    'Fitt nap': 'Fitter Tag',
    'Könnyű nap': 'Leichter Tag',
    'Tiszta nap': 'Clean Day',
    'Zöld nap': 'Grüner Tag',
    'Friss nap': 'Frischer Tag',
    'Tempós nap': 'Schneller Tag',
    'Sietős nap': 'Eiliger Tag',
    'Okos nap': 'Cleverer Tag',
    'Egyszerű nap': 'Einfacher Tag',
    'Dobozolós nap': 'Boxen-Tag',
    'Előre főzős nap': 'Vorkoch-Tag',
    'Protein zabkása bogyós gyümölccsel': 'Protein-Porridge mit Beeren',
    'Tojásos avokádós pirítós': 'Ei-Avocado-Toast',
    'Görög joghurtos granola pohár': 'Griechischer Joghurt-Granola-Becher',
    'Túrós zabpalacsinta': 'Quark-Hafer-Pancakes',
    'Pulykás tojásos wrap': 'Puten-Ei-Wrap',
    'Almás fahéjas overnight oats': 'Apfel-Zimt-Overnight-Oats',
    'Lazacos krémsajtos bagel': 'Lachs-Frischkäse-Bagel',
    'Zöldséges omlett': 'Gemüseomelett',
    'Banános mogyoróvajas smoothie': 'Bananen-Erdnussbutter-Smoothie',
    'Sós cottage cheese tál': 'Herzhafte Cottage-Cheese-Bowl',
    'Csirkés rizses fit bowl': 'Hähnchen-Reis-Fit-Bowl',
    'Pulykás bolognai tészta': 'Puten-Bolognese-Pasta',
    'Lazacos burgonyás ebéd': 'Lachs-Kartoffel-Mittagessen',
    'Marhahúsos bulgur serpenyő': 'Rindfleisch-Bulgur-Pfanne',
    'Tofus zöldséges noodle box': 'Tofu-Gemüse-Noodle-Box',
    'Csicseriborsó curry rizzsel': 'Kichererbsencurry mit Reis',
    'Sertésszűz kuszkusszal': 'Schweinefilet mit Couscous',
    'Lencsés feta saláta': 'Linsen-Feta-Salat',
    'Csirkés pita tál': 'Hähnchen-Pita-Bowl',
    'Tonhalas kukoricás tésztasaláta': 'Thunfisch-Mais-Nudelsalat',
    'Könnyű csirkés saláta': 'Leichter Hähnchensalat',
    'Tojásos zöldséges rizs': 'Ei-Gemüse-Reis',
    'Pulykagolyók cukkinispagettivel': 'Putenbällchen mit Zucchini-Spaghetti',
    'Sült hal zöldségágyon': 'Gebackener Fisch auf Gemüse',
    'Cottage cheese zöldségtál': 'Cottage-Cheese-Gemüseteller',
    'Garnélás quinoa bowl': 'Garnelen-Quinoa-Bowl',
    'Könnyű babos chili': 'Leichtes Bohnen-Chili',
    'Sonkás sajtos omlett': 'Schinken-Käse-Omelett',
    'Töltött paprika light módra': 'Leichte gefüllte Paprika',
    'Görög csirkés tányér': 'Griechischer Hähnchenteller',
    'Protein joghurt pohár': 'Protein-Joghurt-Becher',
    'Almaszeletek mogyoróvajjal': 'Apfelscheiben mit Erdnussbutter',
    'Rizsszelet cottage cheese-zel': 'Reiswaffeln mit Cottage Cheese',
    'Banános kakaós falatok': 'Bananen-Kakao-Bites',
    'Hummuszos zöldségdoboz': 'Hummus-Gemüsebox',
    'Fehérjés puding': 'Protein-Pudding',
    'Főtt tojás avokádóval': 'Gekochte Eier mit Avocado',
    'Tonhalas ropogós falatok': 'Knusprige Thunfisch-Häppchen',
    'Túrós bogyós tál': 'Quark-Beeren-Bowl',
    'Mini csirkés wrap': 'Mini-Hähnchen-Wrap',
    'Csirkés rizses fit bowl kisebb adagban':
        'Hähnchen-Reis-Fit-Bowl, kleinere Portion',
    'Pulykás bolognai tészta light adagban':
        'Puten-Bolognese-Pasta, leichte Portion',
    'Fehérjés puding fél adag gyümölccsel': 'Halber Protein-Pudding mit Obst',
    'Görög joghurtos granola pohár gluténmentes granolával':
        'Griechischer Joghurt-Granola-Becher mit glutenfreiem Granola',
    'Overnight oats előre bekészítve': 'Vorbereitete Overnight Oats',
    'Túrós zabpalacsinta előre sütve': 'Vorgebackene Quark-Hafer-Pancakes',
    'Főétel': 'Hauptgericht',
    'Köret': 'Beilage',
    'Új étel': 'Neues Essen',
    'Új étel hozzáadása': 'Neues Essen hinzufügen',
    'Étel neve': 'Name des Essens',
    'Nyers g': 'Roh g',
    'Kész g': 'Gekocht g',
    'Kimért g': 'Portion g',
    'Nyers adag': 'Rohe Menge',
    'Kész súly': 'Gekochtes Gewicht',
    'Kész étel': 'Gekochtes Essen',
    'Kész étel súlya': 'Gewicht nach dem Kochen',
    'Kimért adag': 'Abgewogene Portion',
    'Nyers egyenérték': 'Rohäquivalent',
    'Bevásárlás+': 'Einkauf+',
    'Meal Prep+': 'Meal Prep+',
    'Új meal prep terv': 'Neuer Meal-Prep-Plan',
    'Elmentett meal prep tervek': 'Gespeicherte Meal-Prep-Pläne',
    'Még nincs elmentett meal prep terved.':
        'Du hast noch keinen gespeicherten Meal-Prep-Plan.',
    'Először ments el egy ételt a meal prep tervezéshez.':
        'Speichere zuerst ein Essen, um Meal Prep zu planen.',
    'Ingyenes módban 1 meal prep tervet menthetsz. A további tervekhez Pro szükséges.':
        'Im kostenlosen Modus kannst du 1 Meal-Prep-Plan speichern. Weitere Pläne benötigen Pro.',
    'Válassz ételt és adagold dobozokra':
        'Wähle ein Essen und teile es in Boxen auf',
    'Válassz főételt, köretet és adagold dobozokra':
        'Wähle Hauptgericht, Beilage und teile alles in Boxen auf',
    'Meal prep terv szerkesztése': 'Meal-Prep-Plan bearbeiten',
    'Teljes mennyiség elosztása': 'Gesamtmenge aufteilen',
    'Fix adagméret': 'Feste Portionsgröße',
    'Az app a mentett kész mennyiséget osztja el az adagok között.':
        'Die App teilt die gespeicherte gekochte Menge auf die Portionen auf.',
    'Te adod meg, hány gramm kerüljön egy adagba.':
        'Du legst fest, wie viele Gramm in eine Portion kommen.',
    'Terv neve': 'Planname',
    'Mentett étel': 'Gespeichertes Essen',
    'Köret hozzáadása': 'Beilage hinzufügen',
    'Nincs köret': 'Keine Beilage',
    'Nincs mentett étel': 'Kein gespeichertes Essen',
    'Adagok': 'Portionen',
    'g / adag': 'g / Portion',
    'Főétel g / adag': 'Hauptgericht g / Portion',
    'Köret g / adag': 'Beilage g / Portion',
    'Megjegyzés': 'Notiz',
    'Szükséges kész étel': 'Benötigtes gekochtes Essen',
    'Szükséges nyers alapanyag': 'Benötigte rohe Zutaten',
    'Szükséges kész főétel': 'Benötigtes gekochtes Hauptgericht',
    'Szükséges nyers főétel': 'Benötigtes rohes Hauptgericht',
    'Főétel adag / doboz': 'Hauptgericht-Portion / Box',
    'Főétel recept szorzó': 'Hauptgericht-Rezeptfaktor',
    'Szükséges kész köret': 'Benötigte gekochte Beilage',
    'Szükséges nyers köret': 'Benötigte rohe Beilage',
    'Köret adag / doboz': 'Beilagenportion / Box',
    'Köret recept szorzó': 'Beilagen-Rezeptfaktor',
    'Köret nyers egyenértéke': 'Rohäquivalent der Beilage',
    'Recept szorzó': 'Rezeptfaktor',
    'Egy adag nyers egyenértéke': 'Rohäquivalent pro Portion',
    'Dobozok': 'Boxen',
    'adag': 'Portion',
    'Szerkesztés': 'Bearbeiten',
    'Új bevásárlólista': 'Neue Einkaufsliste',
    'Bevásárlólista szerkesztése': 'Einkaufsliste bearbeiten',
    'Bevásárlólista törlése': 'Einkaufsliste löschen',
    'Biztosan törlöd ezt a bevásárlólistát?':
        'Möchtest du diese Einkaufsliste wirklich löschen?',
    'Elmentett listák': 'Gespeicherte Listen',
    'Még nincs elmentett bevásárlólistád.':
        'Du hast noch keine gespeicherte Einkaufsliste.',
    'Nevezd el és add hozzá a tételeket':
        'Benenne sie und füge die Artikel hinzu',
    'Lista neve': 'Listenname',
    'Pl. Hétvégi főzés': 'Z. B. Wochenendkochen',
    'Hozzávalók': 'Zutaten',
    'Hozzávaló': 'Zutat',
    'Elkészítés': 'Zubereitung',
    'Allergének': 'Allergene',
    'Adagok száma': 'Anzahl Portionen',
    'Összes kalória': 'Kalorien gesamt',
    'perc': 'Min.',
    'Bevásárláshoz adás': 'Zum Einkauf hinzufügen',
    'Bevásárlólista mentése': 'Einkaufsliste speichern',
    'Új lista neve': 'Name der neuen Liste',
    'Mentés új listaként': 'Als neue Liste speichern',
    'Meglévő listához adás': 'Zu bestehender Liste hinzufügen',
    'tétel': 'Artikel',
    'Tétel hozzáadása': 'Artikel hinzufügen',
    'Hozzáadva': 'Hinzugefügt',
    'Jegyzet': 'Notiz',
    'Írj receptet, tippet vagy emlékeztetőt...':
        'Schreibe ein Rezept, einen Tipp oder eine Erinnerung...',
    'Mégse': 'Abbrechen',
    'Mentés': 'Speichern',
    'Mentve': 'Gespeichert',
    'Mealr Pro': 'Mealr Pro',
    'Pro': 'Pro',
    'Korlátlan mentés és extra funkciók': 'Unbegrenztes Speichern und Extras',
    'Több mentés, bevásárlólisták, súlykövetés extrák':
        'Mehr Speicherplätze, Einkaufslisten, Gewichtstracking-Extras',
    'Részletek': 'Details',
    'Próbáld ki ingyen 7 napig': '7 Tage kostenlos testen',
    'Éves csomag −50% kedvezménnyel': 'Jahrespaket mit −50% Rabatt',
    'Kihagyás': 'Überspringen',
    'Az összeget csak a 7. nap után vonjuk le · Bármikor lemondható':
        'Abrechnung erst nach dem 7. Tag · Jederzeit kündbar',
    'FUNKCIÓ': 'FUNKTION',
    'Ingyenes': 'Kostenlos',
    'Ingyenes alapok': 'Kostenlose Grundlagen',
    'Amit már most használhatsz': 'Was du sofort nutzen kannst',
    'Pro-val feloldható extrák': 'Extras mit Pro freischalten',
    'Rendszeres használathoz': 'Für regelmäßige Nutzung',
    'Főétel mentés': 'Hauptgericht speichern',
    'Köret mentés': 'Beilage speichern',
    'Étel megosztás': 'Essen teilen',
    'Bevásárlás+ listák': 'Einkauf+-Listen',
    'Meal Prep tervező': 'Meal-Prep-Planer',
    'Korlátlan étel és meal prep mentés':
        'Unbegrenztes Speichern von Essen und Meal Prep',
    'Korlátlan': 'Unbegrenzt',
    '30/60 napos súlydiagram és statisztika':
        '30/60-Tage-Gewichtsdiagramm und Statistik',
    'Súlykövetés diagram': 'Gewichtstracking-Diagramm',
    'Súlynapló szerkesztés': 'Gewichtslog bearbeiten',
    'Fogyás statisztika': 'Abnehm-Statistik',
    'Témák (6 db)': 'Themes (6)',
    'Havi előfizetés': 'Monatsabo',
    'Éves előfizetés': 'Jahresabo',
    'Bármikor lemondható': 'Jederzeit kündbar',
    '= 1.00€/hó · legjobb ár': '= 1,00€/Monat · bester Preis',
    '/hó': '/Monat',
    '/év': '/Jahr',
    'db': 'Stk.',
    'Nyers súly kalkulátor': 'Rohgewicht-Rechner',
    'Értem, kezdjük el! →': 'Verstanden, los geht’s! →',
    'Tovább': 'Weiter',
    'MIÉRT HASZNOS?': 'WARUM IST ES NÜTZLICH?',
    'A főtt étel súlya változik, a kalória nem.':
        'Das Gewicht gekochter Speisen ändert sich, die Kalorien nicht.',
    'A Mealr azért kell, hogy ne kelljen fejben számolgatnod, amikor főzés után kevesebb vagy több lesz az étel tömege. Beírod a nyers, kész és kimért súlyt, az app pedig megmondja, mennyi nyers alapanyagnak felel meg az adag.':
        'Mealr erspart Kopfrechnen, wenn Essen nach dem Kochen weniger oder mehr wiegt. Gib Rohgewicht, gekochtes Gewicht und Portion ein, und die App zeigt das Rohäquivalent deiner Portion.',
    'Így pontosabban tudod vezetni a kalóriákat, és a meal prep adagolás sem lesz találgatás.':
        'So trackst du Kalorien genauer, und Meal-Prep-Portionen sind kein Ratespiel mehr.',
    'mérd le főzés előtt az alapanyagokat, például csirke + rizs + zöldség összesen 950 g.':
        'wiege die Zutaten vor dem Kochen, zum Beispiel Hähnchen + Reis + Gemüse zusammen 950 g.',
    'főzés után mérd le az egész elkészült ételt, például 760 g.':
        'wiege nach dem Kochen das fertige Gericht, zum Beispiel 760 g.',
    'ha a dobozodba 250 g kerül, a Mealr kiszámolja, hogy ez kb. 313 g nyers alapanyagnak felel meg.':
        'wenn 250 g in deine Box kommen, berechnet Mealr, dass das etwa 313 g rohen Zutaten entspricht.',
    'Köret külön vezetve': 'Beilagen separat tracken',
    'Ha csak rizst, bulgurt vagy tésztát főzöl köretnek, ugyanígy működik: nyers rizs 300 g, kész rizs 820 g, kimért adag 180 g. Az app megadja a nyers rizs egyenértékét.':
        'Wenn du nur Reis, Bulgur oder Pasta als Beilage kochst, funktioniert es genauso: roher Reis 300 g, gekochter Reis 820 g, Portion 180 g. Die App gibt das Rohreis-Äquivalent aus.',
    'Külön köretnél is ugyanígy működik: ha a nyers alapanyag főzés közben vizet vesz fel, a kész tömeg több lehet, de ettől nem lesz több benne a kalória. A Mealr ilyenkor is a nyers egyenértéket számolja ki.':
        'Bei separaten Beilagen funktioniert es genauso: Wenn eine rohe Zutat beim Kochen Wasser aufnimmt, kann das fertige Gewicht höher sein, aber dadurch entstehen keine zusätzlichen Kalorien. Mealr berechnet trotzdem das Rohäquivalent.',
    'MINDEN EGYBEN': 'ALLES IN EINEM',
    'Nem csak mérlegelés: egy app a kajás rutinodhoz.':
        'Nicht nur Wiegen: eine App für deine Essensroutine.',
    'A Mealr egy helyre gyűjti a főzéshez, adagoláshoz és célkövetéshez hasznos eszközöket, hogy ne több app között kelljen ugrálnod.':
        'Mealr bündelt Tools fürs Kochen, Portionieren und Zieltracking an einem Ort, damit du nicht zwischen mehreren Apps wechseln musst.',
    'Kalória kalkulátor': 'Kalorienrechner',
    'BMI': 'BMI',
    'Bevásárlás lista': 'Einkaufsliste',
    'Súly követés': 'Gewichtstracking',
    'Meal preppelés': 'Meal Prep',
    'MI A PROBLÉMA?': 'WAS IST DAS PROBLEM?',
    'Főzés során az étel ': 'Beim Kochen verliert Essen ',
    'veszít a tömegéből': 'an Gewicht',
    ' – de nem a kalóriájából. Ha a kész súlyt írod be a kalóriaszámlálóba, ':
        ' - aber nicht an Kalorien. Wenn du das gekochte Gewicht einträgst, ',
    'téves értéket kapsz.': 'erhältst du einen falschen Wert.',
    'Főzés során az étel tömege ': 'Beim Kochen kann das Gewicht des Essens ',
    'csökkenhet vagy növekedhet': 'sinken oder steigen',
    ', de ettől ': ', aber dadurch ',
    'nem változik a kalóriája.': 'ändern sich die Kalorien nicht.',
    'HOGYAN SEGÍT A MEALR?': 'WIE HILFT MEALR?',
    'a száraz, nyers hozzávalók össztömege főzés előtt':
        'das Gesamtgewicht der trockenen, rohen Zutaten vor dem Kochen',
    'az étel össztömege főzés vagy sütés után':
        'das Gesamtgewicht nach dem Kochen oder Backen',
    'amit a tányérra teszel → megkapod a ':
        'was du auf den Teller legst → du bekommst das ',
    'nyers egyenértéket': 'Rohäquivalent',
    'A mentett ételekhez bármikor visszatérhetsz – naponta csak a kimért adagot kell módosítani.':
        'Du kannst jederzeit zu gespeicherten Essen zurückkehren - täglich änderst du nur die Portion.',
    'Kalória\nkalkulátor': 'Kalorien-\nrechner',
    'Számold ki a napi szintentartó kalóriádat életkor, súly, magasság és aktivitás alapján.':
        'Berechne deine Erhaltungskalorien nach Alter, Gewicht, Größe und Aktivität.',
    'BMI\nkalkulátor': 'BMI-\nRechner',
    'Ellenőrizd az ideális testsúlyod és kövesd nyomon a változásokat. Mentve a profilodba.':
        'Prüfe dein Idealgewicht und verfolge Änderungen. Im Profil gespeichert.',
    'Hogyan működik?': 'Wie funktioniert es?',
    ', de ': ', aber ',
    'nem a kalóriájából.': 'nicht an Kalorien.',
    ' Ha a kész súlyt írod be a kalóriaszámlálóba, téves értéket kapsz.':
        ' Wenn du das gekochte Gewicht einträgst, erhältst du einen falschen Wert.',
    'Add össze a száraz, nyers hozzávalókat főzés ':
        'Addiere die trockenen, rohen Zutaten ',
    'előtt': 'vor dem Kochen',
    ' – ezt mérd le és írd be.': ' - wiege sie und trage sie ein.',
    'Ha megfőzted vagy megsütötted az ételt, mérd le az ':
        'Nach dem Kochen oder Backen wiegst du das ',
    'össztömeget': 'Gesamtgewicht',
    ' és írd be ide.': ' und trägst es hier ein.',
    'Ha enni szeretnél, mérd le a tányérodra kerülő adagot és írd be – megkapod a ':
        'Wenn du essen möchtest, wiege die Portion auf deinem Teller und trage sie ein - du bekommst das ',
    'nyers egyenértéket.': 'Rohäquivalent.',
    'Képlet: ': 'Formel: ',
    'nyers ÷ kész × kimért =\nnyers egyenérték\n':
        'roh ÷ gekocht × Portion =\nRohäquivalent\n',
    '→ Ezt a számot írd be a kalóriaszámlálódba\n(pl. MyFitnessPal, Cronometer stb.)':
        '→ Trage diese Zahl in deinen Kalorienzähler ein\n(z. B. MyFitnessPal, Cronometer usw.)',
    'Bezárás': 'Schließen',
    'TESTTÖMEG INDEX (BMI)': 'BODY-MASS-INDEX (BMI)',
    'Sovány': 'Untergewicht',
    'Normál': 'Normal',
    'Normál súly': 'Normalgewicht',
    'Túlsúly': 'Übergewicht',
    'Túlsúlyos': 'Übergewicht',
    'Obezitás': 'Adipositas',
    'Ideális testsúly': 'Idealgewicht',
    'A BMI csak tájékoztató. Nem veszi figyelembe az izomtömeget. Orvosi diagnózisra nem alkalmas.':
        'Der BMI dient nur zur Orientierung. Er berücksichtigt keine Muskelmasse und ist keine medizinische Diagnose.',
    'A BMI 18.5 alatt sovány tartomány.': 'BMI unter 18,5 ist Untergewicht.',
    'A normál BMI tartomány 18.5–24.9. Egészséges testsúlyon vagy!':
        'Der normale BMI-Bereich liegt bei 18,5-24,9. Du bist im gesunden Bereich!',
    'A BMI 25–29.9 között túlsúly.': 'BMI zwischen 25-29,9 ist Übergewicht.',
    'A BMI 30 felett obezitás tartomány.': 'BMI über 30 ist Adipositas.',
    'Nem': 'Geschlecht',
    'Férfi': 'Männlich',
    'Nő': 'Weiblich',
    'Súly (kg)': 'Gewicht (kg)',
    'Magasság (cm)': 'Größe (cm)',
    'Mentve a profilba.': 'Im Profil gespeichert.',
    'Mentve a profilba · legközelebb automatikusan kitöltve':
        'Im Profil gespeichert · nächstes Mal automatisch ausgefüllt',
    'NAPI SZINTENTARTÓ KALÓRIA': 'TÄGLICHE ERHALTUNGSKALORIEN',
    'kcal / nap': 'kcal / Tag',
    'Fogyáshoz': 'Zum Abnehmen',
    'Tömegnövelés': 'Zum Zunehmen',
    'Életkor': 'Alter',
    'Napi aktivitás': 'Tägliche Aktivität',
    'Ülő életmód': 'Sitzend',
    'Enyhén aktív (heti 1–3x)': 'Leicht aktiv (1-3x/Woche)',
    'Közepesen aktív (heti 3–5x)': 'Mäßig aktiv (3-5x/Woche)',
    'Erősen aktív (heti 6–7x)': 'Sehr aktiv (6-7x/Woche)',
    'Extrém aktív': 'Extrem aktiv',
    'HOGYAN HASZNÁLD?': 'WIE VERWENDEST DU ES?',
    'Fogyáshoz: ': 'Zum Abnehmen: ',
    'vonj le 300–500 kcal-t. Napi 500 kcal deficit ≈ heti 0,5 kg fogyás.\n\n':
        'ziehe 300-500 kcal ab. Ein tägliches Defizit von 500 kcal entspricht ca. 0,5 kg pro Woche.\n\n',
    'Tömegnöveléshez: ': 'Zum Zunehmen: ',
    'adj 150–300 kcal-t a szintentartóhoz.\n\n':
        'füge 150-300 kcal zum Erhalt hinzu.\n\n',
    'Iránymutató – 2–4 hétig kövesd, majd a tényleges változás alapján igazítsd.':
        'Als Richtwert 2-4 Wochen verfolgen und dann nach tatsächlicher Veränderung anpassen.',
    'Mentés profilba · a Kalória cél frissítése':
        'Im Profil speichern · Kalorienziel aktualisieren',
    'Személyes adatok': 'Persönliche Daten',
    'Súly': 'Gewicht',
    'Magasság': 'Größe',
    'Kalória cél': 'Kalorienziel',
    'Kalkulátorból beállítva': 'Vom Rechner gesetzt',
    'Súlykövetés': 'Gewichtstracking',
    'Súly progresszió': 'Gewichtsverlauf',
    'Adj hozzá legalább két súlyt a diagramhoz.':
        'Füge mindestens zwei Gewichtswerte hinzu, um das Diagramm zu sehen.',
    'nap': 'Tage',
    'Hozzáadás': 'Hinzufügen',
    'Rögzített súlyok': 'Gespeicherte Gewichte',
    'További rögzítések': 'Mehr Einträge anzeigen',
    'Kevesebb mutatása': 'Weniger anzeigen',
    'Progresszió törlése': 'Verlauf löschen',
    'Biztosan törlöd az összes rögzített súlyt?':
        'Möchtest du wirklich alle gespeicherten Gewichtswerte löschen?',
    'Törlés': 'Löschen',
    'Súly szerkesztése': 'Gewicht bearbeiten',
    'Nincs változás a kezdő súlyhoz képest':
        'Keine Veränderung im Vergleich zum Startgewicht',
    'Eddigi fogyás': 'Bisher abgenommen',
    'Eddigi változás': 'Bisherige Veränderung',
    'Pro statisztika': 'Pro-Statistik',
    'Összes': 'Gesamt',
    '7 nap': '7 Tage',
    '30 nap': '30 Tage',
    'Heti átlag': 'Wochendurchschnitt',
    'hét': 'Woche',
    'Trend': 'Trend',
    'Legalacsonyabb': 'Niedrigstes',
    'Csökkenő': 'Fallend',
    'Stagnál': 'Stabil',
    'Emelkedő': 'Steigend',
    'Beállítások': 'Einstellungen',
    'Nyelv, téma, mód és verzió': 'Sprache, Theme, Modus und Version',
    'Téma': 'Theme',
    'Nyelv': 'Sprache',
    'Sötét mód': 'Dunkler Modus',
    'Előfizetés': 'Abo',
    'Pro mód teszt': 'Pro-Modus-Test',
    'Verzió 1.0.0': 'Version 1.0.0',
    'Aktív előfizetés · ': 'Aktives Abo · ',
    ' Pro extrák lezárva': ' · Pro-Extras gesperrt',
    'Nincs aktív előfizetés': 'Kein aktives Abo',
    'Lejár: ': 'Läuft ab: ',
    'Alapértelmezett: English': 'Standard: English',
    'Téma választása': 'Theme wählen',
  },
  AppLanguage.spanish: {
    'Lista': 'Lista',
    'Kalória': 'Calorías',
    'Profil': 'Perfil',
    'Főételek': 'Platos principales',
    'Köretek': 'Guarniciones',
    'Receptek': 'Recetas',
    'Recept': 'Receta',
    'Kedvencek': 'Favoritos',
    'Reggeli': 'Desayuno',
    'Ebéd': 'Almuerzo',
    'Vacsora': 'Cena',
    'Nasi': 'Snack',
    'Étrendek': 'Planes diarios',
    'Étrend': 'Plan diario',
    'étkezés': 'comidas',
    'Napi bontás': 'Desglose diario',
    'Hamarosan': 'Pronto',
    'Válassz étrend típust': 'Elige un tipo de plan',
    'A konkrét napi étrendeket a következő lépésben töltjük fel.':
        'Añadiremos los planes diarios concretos en el siguiente paso.',
    'Válassz egy típust, majd nézd meg a hozzá tartozó napi étrendeket.':
        'Elige un tipo y mira sus planes diarios.',
    '1500 kcal étrendek': 'Planes de 1500 kcal',
    'Étrend típusok': 'Tipos de plan',
    'Magas fehérje': 'Alto en proteína',
    'Edzéshez és jobb teltségérzethez': 'Para entrenar y sentir más saciedad',
    'Gluténmentes': 'Sin gluten',
    'Glutént tartalmazó alapanyagok nélkül':
        'Sin ingredientes que contengan gluten',
    'Vegetáriánus': 'Vegetariano',
    'Húsmentes napi étrend': 'Plan diario sin carne',
    'Gyors': 'Rápido',
    'Rövid elkészítési idejű ételekkel': 'Con comidas rápidas de preparar',
    'Pénztárcabarát': 'Económico',
    'Egyszerűbb, olcsóbb alapanyagokkal':
        'Con ingredientes más simples y baratos',
    'Meal prep alapú': 'Basado en meal prep',
    'Előre dobozolható napi menü': 'Menú diario para preparar por adelantado',
    'Erős nap': 'Día fuerte',
    'Fitt nap': 'Día fit',
    'Könnyű nap': 'Día ligero',
    'Tiszta nap': 'Día limpio',
    'Zöld nap': 'Día verde',
    'Friss nap': 'Día fresco',
    'Tempós nap': 'Día rápido',
    'Sietős nap': 'Día exprés',
    'Okos nap': 'Día inteligente',
    'Egyszerű nap': 'Día sencillo',
    'Dobozolós nap': 'Día de meal prep',
    'Előre főzős nap': 'Día para cocinar por adelantado',
    'Protein zabkása bogyós gyümölccsel': 'Avena proteica con frutos rojos',
    'Tojásos avokádós pirítós': 'Tostada de huevo y aguacate',
    'Görög joghurtos granola pohár': 'Vaso de yogur griego con granola',
    'Túrós zabpalacsinta': 'Pancakes de avena con requesón',
    'Pulykás tojásos wrap': 'Wrap de pavo y huevo',
    'Almás fahéjas overnight oats': 'Overnight oats de manzana y canela',
    'Lazacos krémsajtos bagel': 'Bagel de salmón con queso crema',
    'Zöldséges omlett': 'Tortilla de verduras',
    'Banános mogyoróvajas smoothie': 'Smoothie de banana y mantequilla de maní',
    'Sós cottage cheese tál': 'Bowl salado de cottage cheese',
    'Csirkés rizses fit bowl': 'Fit bowl de pollo con arroz',
    'Pulykás bolognai tészta': 'Pasta boloñesa de pavo',
    'Lazacos burgonyás ebéd': 'Almuerzo de salmón con patatas',
    'Marhahúsos bulgur serpenyő': 'Sartén de ternera con bulgur',
    'Tofus zöldséges noodle box': 'Noodle box de tofu y verduras',
    'Csicseriborsó curry rizzsel': 'Curry de garbanzos con arroz',
    'Sertésszűz kuszkusszal': 'Solomillo de cerdo con cuscús',
    'Lencsés feta saláta': 'Ensalada de lentejas con feta',
    'Csirkés pita tál': 'Bowl de pita con pollo',
    'Tonhalas kukoricás tésztasaláta': 'Ensalada de pasta con atún y maíz',
    'Könnyű csirkés saláta': 'Ensalada ligera de pollo',
    'Tojásos zöldséges rizs': 'Arroz con huevo y verduras',
    'Pulykagolyók cukkinispagettivel':
        'Albóndigas de pavo con espagueti de calabacín',
    'Sült hal zöldségágyon': 'Pescado al horno sobre verduras',
    'Cottage cheese zöldségtál': 'Plato de cottage cheese con verduras',
    'Garnélás quinoa bowl': 'Bowl de quinoa con gambas',
    'Könnyű babos chili': 'Chili ligero de frijoles',
    'Sonkás sajtos omlett': 'Tortilla de jamón y queso',
    'Töltött paprika light módra': 'Pimientos rellenos ligeros',
    'Görög csirkés tányér': 'Plato griego de pollo',
    'Protein joghurt pohár': 'Vaso de yogur proteico',
    'Almaszeletek mogyoróvajjal': 'Rodajas de manzana con mantequilla de maní',
    'Rizsszelet cottage cheese-zel': 'Tortitas de arroz con cottage cheese',
    'Banános kakaós falatok': 'Bocados de banana y cacao',
    'Hummuszos zöldségdoboz': 'Caja de verduras con hummus',
    'Fehérjés puding': 'Pudin proteico',
    'Főtt tojás avokádóval': 'Huevos cocidos con aguacate',
    'Tonhalas ropogós falatok': 'Bocados crujientes de atún',
    'Túrós bogyós tál': 'Bowl de requesón con frutos rojos',
    'Mini csirkés wrap': 'Mini wrap de pollo',
    'Csirkés rizses fit bowl kisebb adagban':
        'Fit bowl de pollo con arroz, porción pequeña',
    'Pulykás bolognai tészta light adagban':
        'Pasta boloñesa de pavo, porción ligera',
    'Fehérjés puding fél adag gyümölccsel': 'Medio pudin proteico con fruta',
    'Görög joghurtos granola pohár gluténmentes granolával':
        'Vaso de yogur griego con granola sin gluten',
    'Overnight oats előre bekészítve':
        'Overnight oats preparado con antelación',
    'Túrós zabpalacsinta előre sütve':
        'Pancakes de avena con requesón preparados',
    'Főétel': 'Plato principal',
    'Köret': 'Guarnición',
    'Új étel': 'Nuevo alimento',
    'Új étel hozzáadása': 'Añadir nuevo alimento',
    'Étel neve': 'Nombre del alimento',
    'Nyers g': 'Crudo g',
    'Kész g': 'Cocido g',
    'Kimért g': 'Porción g',
    'Nyers adag': 'Cantidad cruda',
    'Kész súly': 'Peso cocido',
    'Kész étel': 'Comida cocida',
    'Kész étel súlya': 'Peso de comida cocida',
    'Kimért adag': 'Porción medida',
    'Nyers egyenérték': 'Equivalente crudo',
    'Bevásárlás+': 'Compra+',
    'Meal Prep+': 'Meal Prep+',
    'Új meal prep terv': 'Nuevo plan de meal prep',
    'Elmentett meal prep tervek': 'Planes de meal prep guardados',
    'Még nincs elmentett meal prep terved.':
        'Aún no tienes un plan de meal prep guardado.',
    'Először ments el egy ételt a meal prep tervezéshez.':
        'Guarda primero una comida para planificar meal prep.',
    'Ingyenes módban 1 meal prep tervet menthetsz. A további tervekhez Pro szükséges.':
        'En el modo gratis puedes guardar 1 plan de meal prep. Para más planes necesitas Pro.',
    'Válassz ételt és adagold dobozokra':
        'Elige una comida y divídela en recipientes',
    'Válassz főételt, köretet és adagold dobozokra':
        'Elige plato principal, guarnición y divídelos en recipientes',
    'Meal prep terv szerkesztése': 'Editar plan de meal prep',
    'Teljes mennyiség elosztása': 'Dividir cantidad total',
    'Fix adagméret': 'Tamaño fijo de porción',
    'Az app a mentett kész mennyiséget osztja el az adagok között.':
        'La app divide la cantidad cocida guardada entre las porciones.',
    'Te adod meg, hány gramm kerüljön egy adagba.':
        'Tú defines cuántos gramos van en cada porción.',
    'Terv neve': 'Nombre del plan',
    'Mentett étel': 'Comida guardada',
    'Köret hozzáadása': 'Añadir guarnición',
    'Nincs köret': 'Sin guarnición',
    'Nincs mentett étel': 'Sin comida guardada',
    'Adagok': 'Porciones',
    'g / adag': 'g / porción',
    'Főétel g / adag': 'Principal g / porción',
    'Köret g / adag': 'Guarnición g / porción',
    'Megjegyzés': 'Nota',
    'Szükséges kész étel': 'Comida cocida necesaria',
    'Szükséges nyers alapanyag': 'Ingredientes crudos necesarios',
    'Szükséges kész főétel': 'Principal cocido necesario',
    'Szükséges nyers főétel': 'Principal crudo necesario',
    'Főétel adag / doboz': 'Principal / recipiente',
    'Főétel recept szorzó': 'Multiplicador del principal',
    'Szükséges kész köret': 'Guarnición cocida necesaria',
    'Szükséges nyers köret': 'Guarnición cruda necesaria',
    'Köret adag / doboz': 'Guarnición / recipiente',
    'Köret recept szorzó': 'Multiplicador de guarnición',
    'Köret nyers egyenértéke': 'Equivalente crudo de guarnición',
    'Recept szorzó': 'Multiplicador de receta',
    'Egy adag nyers egyenértéke': 'Equivalente crudo por porción',
    'Dobozok': 'Recipientes',
    'adag': 'porción',
    'Szerkesztés': 'Editar',
    'Új bevásárlólista': 'Nueva lista de compra',
    'Bevásárlólista szerkesztése': 'Editar lista de compra',
    'Bevásárlólista törlése': 'Eliminar lista de compra',
    'Biztosan törlöd ezt a bevásárlólistát?':
        '¿Seguro que quieres eliminar esta lista de compra?',
    'Elmentett listák': 'Listas guardadas',
    'Még nincs elmentett bevásárlólistád.':
        'Aún no tienes una lista de compra guardada.',
    'Nevezd el és add hozzá a tételeket': 'Ponle nombre y añade artículos',
    'Lista neve': 'Nombre de la lista',
    'Pl. Hétvégi főzés': 'P. ej. cocina del fin de semana',
    'Hozzávalók': 'Ingredientes',
    'Hozzávaló': 'Ingrediente',
    'Elkészítés': 'Preparación',
    'Allergének': 'Alérgenos',
    'Adagok száma': 'Número de porciones',
    'Összes kalória': 'Calorías totales',
    'perc': 'min',
    'Bevásárláshoz adás': 'Añadir a la compra',
    'Bevásárlólista mentése': 'Guardar lista de compra',
    'Új lista neve': 'Nombre de la nueva lista',
    'Mentés új listaként': 'Guardar como nueva lista',
    'Meglévő listához adás': 'Añadir a lista existente',
    'tétel': 'artículos',
    'Tétel hozzáadása': 'Añadir artículo',
    'Hozzáadva': 'Añadido',
    'Jegyzet': 'Nota',
    'Írj receptet, tippet vagy emlékeztetőt...':
        'Escribe una receta, consejo o recordatorio...',
    'Mégse': 'Cancelar',
    'Mentés': 'Guardar',
    'Mentve': 'Guardado',
    'Mealr Pro': 'Mealr Pro',
    'Pro': 'Pro',
    'Korlátlan mentés és extra funkciók':
        'Guardado ilimitado y funciones extra',
    'Több mentés, bevásárlólisták, súlykövetés extrák':
        'Más guardados, listas de compra y extras de peso',
    'Részletek': 'Detalles',
    'Próbáld ki ingyen 7 napig': 'Pruébalo gratis 7 días',
    'Éves csomag −50% kedvezménnyel': 'Plan anual con −50% de descuento',
    'Kihagyás': 'Omitir',
    'Az összeget csak a 7. nap után vonjuk le · Bármikor lemondható':
        'Se cobra solo después del día 7 · Cancela cuando quieras',
    'FUNKCIÓ': 'FUNCIÓN',
    'Ingyenes': 'Gratis',
    'Ingyenes alapok': 'Funciones gratis',
    'Amit már most használhatsz': 'Lo que puedes usar ahora',
    'Pro-val feloldható extrák': 'Extras desbloqueados con Pro',
    'Rendszeres használathoz': 'Para uso regular',
    'Főétel mentés': 'Guardar plato principal',
    'Köret mentés': 'Guardar guarnición',
    'Étel megosztás': 'Compartir alimento',
    'Bevásárlás+ listák': 'Listas de Compra+',
    'Meal Prep tervező': 'Planificador Meal Prep',
    'Korlátlan étel és meal prep mentés':
        'Guardado ilimitado de comidas y meal prep',
    'Korlátlan': 'Ilimitado',
    '30/60 napos súlydiagram és statisztika':
        'Gráfico de peso de 30/60 días y estadísticas',
    'Súlykövetés diagram': 'Gráfico de seguimiento de peso',
    'Súlynapló szerkesztés': 'Editar registro de peso',
    'Fogyás statisztika': 'Estadísticas de pérdida de peso',
    'Témák (6 db)': 'Temas (6)',
    'Havi előfizetés': 'Suscripción mensual',
    'Éves előfizetés': 'Suscripción anual',
    'Bármikor lemondható': 'Cancela cuando quieras',
    '= 1.00€/hó · legjobb ár': '= 1,00€/mes · mejor precio',
    '/hó': '/mes',
    '/év': '/año',
    'db': 'uds.',
    'Nyers súly kalkulátor': 'Calculadora de peso crudo',
    'Értem, kezdjük el! →': 'Entendido, empecemos →',
    'Tovább': 'Siguiente',
    'MIÉRT HASZNOS?': '¿POR QUÉ ES ÚTIL?',
    'A főtt étel súlya változik, a kalória nem.':
        'El peso de la comida cocida cambia, las calorías no.',
    'A Mealr azért kell, hogy ne kelljen fejben számolgatnod, amikor főzés után kevesebb vagy több lesz az étel tömege. Beírod a nyers, kész és kimért súlyt, az app pedig megmondja, mennyi nyers alapanyagnak felel meg az adag.':
        'Mealr evita cálculos mentales cuando la comida pesa menos o más después de cocinar. Introduce peso crudo, cocido y porción, y la app te dice el equivalente crudo de tu ración.',
    'Így pontosabban tudod vezetni a kalóriákat, és a meal prep adagolás sem lesz találgatás.':
        'Así registras calorías con más precisión y las porciones de meal prep dejan de ser una suposición.',
    'mérd le főzés előtt az alapanyagokat, például csirke + rizs + zöldség összesen 950 g.':
        'pesa los ingredientes antes de cocinar, por ejemplo pollo + arroz + verduras con un total de 950 g.',
    'főzés után mérd le az egész elkészült ételt, például 760 g.':
        'después de cocinar, pesa todo el plato terminado, por ejemplo 760 g.',
    'ha a dobozodba 250 g kerül, a Mealr kiszámolja, hogy ez kb. 313 g nyers alapanyagnak felel meg.':
        'si pones 250 g en tu recipiente, Mealr calcula que equivale a unos 313 g de ingredientes crudos.',
    'Köret külön vezetve': 'Guarniciones por separado',
    'Ha csak rizst, bulgurt vagy tésztát főzöl köretnek, ugyanígy működik: nyers rizs 300 g, kész rizs 820 g, kimért adag 180 g. Az app megadja a nyers rizs egyenértékét.':
        'Si cocinas solo arroz, bulgur o pasta como guarnición, funciona igual: arroz crudo 300 g, arroz cocido 820 g, porción 180 g. La app da el equivalente de arroz crudo.',
    'Külön köretnél is ugyanígy működik: ha a nyers alapanyag főzés közben vizet vesz fel, a kész tömeg több lehet, de ettől nem lesz több benne a kalória. A Mealr ilyenkor is a nyers egyenértéket számolja ki.':
        'Con guarniciones separadas funciona igual: si un ingrediente crudo absorbe agua al cocinarse, el peso cocido puede ser mayor, pero eso no añade calorías. Mealr sigue calculando el equivalente crudo.',
    'MINDEN EGYBEN': 'TODO EN UNO',
    'Nem csak mérlegelés: egy app a kajás rutinodhoz.':
        'No solo pesar: una app para tu rutina de comida.',
    'A Mealr egy helyre gyűjti a főzéshez, adagoláshoz és célkövetéshez hasznos eszközöket, hogy ne több app között kelljen ugrálnod.':
        'Mealr reúne herramientas para cocinar, porcionar y seguir objetivos en un solo lugar, para no saltar entre varias apps.',
    'Kalória kalkulátor': 'Calculadora de calorías',
    'BMI': 'BMI',
    'Bevásárlás lista': 'Lista de compra',
    'Súly követés': 'Seguimiento de peso',
    'Meal preppelés': 'Meal prep',
    'MI A PROBLÉMA?': '¿CUÁL ES EL PROBLEMA?',
    'Főzés során az étel ': 'Al cocinar, la comida ',
    'veszít a tömegéből': 'pierde peso',
    ' – de nem a kalóriájából. Ha a kész súlyt írod be a kalóriaszámlálóba, ':
        ', pero no calorías. Si introduces el peso cocido en tu contador, ',
    'téves értéket kapsz.': 'obtendrás un valor incorrecto.',
    'Főzés során az étel tömege ': 'Al cocinar, el peso de la comida ',
    'csökkenhet vagy növekedhet': 'puede disminuir o aumentar',
    ', de ettől ': ', pero eso ',
    'nem változik a kalóriája.': 'no cambia sus calorías.',
    'HOGYAN SEGÍT A MEALR?': '¿CÓMO AYUDA MEALR?',
    'a száraz, nyers hozzávalók össztömege főzés előtt':
        'el peso total de ingredientes secos y crudos antes de cocinar',
    'az étel össztömege főzés vagy sütés után':
        'el peso total después de cocinar u hornear',
    'amit a tányérra teszel → megkapod a ':
        'lo que pones en el plato → obtienes el ',
    'nyers egyenértéket': 'equivalente crudo',
    'A mentett ételekhez bármikor visszatérhetsz – naponta csak a kimért adagot kell módosítani.':
        'Puedes volver a los alimentos guardados cuando quieras; cada día solo ajustas la porción medida.',
    'Kalória\nkalkulátor': 'Calculadora\nde calorías',
    'Számold ki a napi szintentartó kalóriádat életkor, súly, magasság és aktivitás alapján.':
        'Calcula tus calorías de mantenimiento según edad, peso, altura y actividad.',
    'BMI\nkalkulátor': 'Calculadora\nBMI',
    'Ellenőrizd az ideális testsúlyod és kövesd nyomon a változásokat. Mentve a profilodba.':
        'Comprueba tu peso ideal y sigue los cambios. Guardado en tu perfil.',
    'Hogyan működik?': '¿Cómo funciona?',
    ', de ': ', pero ',
    'nem a kalóriájából.': 'no calorías.',
    ' Ha a kész súlyt írod be a kalóriaszámlálóba, téves értéket kapsz.':
        ' Si introduces el peso cocido en tu contador, obtendrás un valor incorrecto.',
    'Add össze a száraz, nyers hozzávalókat főzés ':
        'Suma los ingredientes secos y crudos ',
    'előtt': 'antes de cocinar',
    ' – ezt mérd le és írd be.': '; pésalo e introdúcelo.',
    'Ha megfőzted vagy megsütötted az ételt, mérd le az ':
        'Después de cocinar u hornear, mide el ',
    'össztömeget': 'peso total',
    ' és írd be ide.': ' e introdúcelo aquí.',
    'Ha enni szeretnél, mérd le a tányérodra kerülő adagot és írd be – megkapod a ':
        'Cuando quieras comer, pesa la porción del plato e introdúcela; obtendrás el ',
    'nyers egyenértéket.': 'equivalente crudo.',
    'Képlet: ': 'Fórmula: ',
    'nyers ÷ kész × kimért =\nnyers egyenérték\n':
        'crudo ÷ cocido × porción =\nequivalente crudo\n',
    '→ Ezt a számot írd be a kalóriaszámlálódba\n(pl. MyFitnessPal, Cronometer stb.)':
        '→ Introduce este número en tu contador de calorías\n(p. ej. MyFitnessPal, Cronometer, etc.)',
    'Bezárás': 'Cerrar',
    'TESTTÖMEG INDEX (BMI)': 'ÍNDICE DE MASA CORPORAL (BMI)',
    'Sovány': 'Bajo peso',
    'Normál': 'Normal',
    'Normál súly': 'Peso normal',
    'Túlsúly': 'Sobrepeso',
    'Túlsúlyos': 'Sobrepeso',
    'Obezitás': 'Obesidad',
    'Ideális testsúly': 'Peso ideal',
    'A BMI csak tájékoztató. Nem veszi figyelembe az izomtömeget. Orvosi diagnózisra nem alkalmas.':
        'El BMI es solo orientativo. No considera la masa muscular y no es un diagnóstico médico.',
    'A BMI 18.5 alatt sovány tartomány.':
        'BMI por debajo de 18,5 indica bajo peso.',
    'A normál BMI tartomány 18.5–24.9. Egészséges testsúlyon vagy!':
        'El rango normal de BMI es 18,5-24,9. Estás en un rango saludable.',
    'A BMI 25–29.9 között túlsúly.': 'BMI entre 25-29,9 indica sobrepeso.',
    'A BMI 30 felett obezitás tartomány.': 'BMI superior a 30 indica obesidad.',
    'Nem': 'Género',
    'Férfi': 'Hombre',
    'Nő': 'Mujer',
    'Súly (kg)': 'Peso (kg)',
    'Magasság (cm)': 'Altura (cm)',
    'Mentve a profilba.': 'Guardado en el perfil.',
    'Mentve a profilba · legközelebb automatikusan kitöltve':
        'Guardado en el perfil · se rellena automáticamente la próxima vez',
    'NAPI SZINTENTARTÓ KALÓRIA': 'CALORÍAS DIARIAS DE MANTENIMIENTO',
    'kcal / nap': 'kcal / día',
    'Fogyáshoz': 'Para perder grasa',
    'Tömegnövelés': 'Para ganar masa',
    'Életkor': 'Edad',
    'Napi aktivitás': 'Actividad diaria',
    'Ülő életmód': 'Sedentario',
    'Enyhén aktív (heti 1–3x)': 'Ligeramente activo (1-3x/semana)',
    'Közepesen aktív (heti 3–5x)': 'Moderadamente activo (3-5x/semana)',
    'Erősen aktív (heti 6–7x)': 'Muy activo (6-7x/semana)',
    'Extrém aktív': 'Extremadamente activo',
    'HOGYAN HASZNÁLD?': '¿CÓMO USARLO?',
    'Fogyáshoz: ': 'Para perder grasa: ',
    'vonj le 300–500 kcal-t. Napi 500 kcal deficit ≈ heti 0,5 kg fogyás.\n\n':
        'resta 300-500 kcal. Un déficit diario de 500 kcal equivale a unos 0,5 kg por semana.\n\n',
    'Tömegnöveléshez: ': 'Para ganar masa: ',
    'adj 150–300 kcal-t a szintentartóhoz.\n\n':
        'añade 150-300 kcal al mantenimiento.\n\n',
    'Iránymutató – 2–4 hétig kövesd, majd a tényleges változás alapján igazítsd.':
        'Úsalo como guía durante 2-4 semanas y ajusta según el cambio real.',
    'Mentés profilba · a Kalória cél frissítése':
        'Guardar en perfil · actualizar objetivo de calorías',
    'Személyes adatok': 'Datos personales',
    'Súly': 'Peso',
    'Magasság': 'Altura',
    'Kalória cél': 'Objetivo de calorías',
    'Kalkulátorból beállítva': 'Configurado desde calculadora',
    'Súlykövetés': 'Seguimiento de peso',
    'Súly progresszió': 'Progreso de peso',
    'Adj hozzá legalább két súlyt a diagramhoz.':
        'Añade al menos dos pesos para mostrar el gráfico.',
    'nap': 'días',
    'Hozzáadás': 'Añadir',
    'Rögzített súlyok': 'Pesos registrados',
    'További rögzítések': 'Mostrar más registros',
    'Kevesebb mutatása': 'Mostrar menos',
    'Progresszió törlése': 'Eliminar progreso',
    'Biztosan törlöd az összes rögzített súlyt?':
        '¿Seguro que quieres eliminar todos los pesos registrados?',
    'Törlés': 'Eliminar',
    'Súly szerkesztése': 'Editar peso',
    'Nincs változás a kezdő súlyhoz képest':
        'Sin cambios respecto al peso inicial',
    'Eddigi fogyás': 'Peso perdido hasta ahora',
    'Eddigi változás': 'Cambio total hasta ahora',
    'Pro statisztika': 'Estadísticas Pro',
    'Összes': 'Total',
    '7 nap': '7 días',
    '30 nap': '30 días',
    'Heti átlag': 'Media semanal',
    'hét': 'semana',
    'Trend': 'Tendencia',
    'Legalacsonyabb': 'Más bajo',
    'Csökkenő': 'Bajando',
    'Stagnál': 'Estable',
    'Emelkedő': 'Subiendo',
    'Beállítások': 'Ajustes',
    'Nyelv, téma, mód és verzió': 'Idioma, tema, modo y versión',
    'Téma': 'Tema',
    'Nyelv': 'Idioma',
    'Sötét mód': 'Modo oscuro',
    'Előfizetés': 'Suscripción',
    'Pro mód teszt': 'Prueba modo Pro',
    'Verzió 1.0.0': 'Versión 1.0.0',
    'Aktív előfizetés · ': 'Suscripción activa · ',
    ' Pro extrák lezárva': ' · Extras Pro bloqueados',
    'Nincs aktív előfizetés': 'Sin suscripción activa',
    'Lejár: ': 'Expira: ',
    'Alapértelmezett: English': 'Predeterminado: English',
    'Téma választása': 'Elegir tema',
  },
};
