import '../../models/recipe.dart';

const breakfastRecipes = [
  Recipe(
    id: 'protein_oat_bowl',
    category: RecipeCategory.breakfast,
    name: 'Protein zabkása bogyós gyümölccsel',
    emoji: '🥣',
    baseServings: 1,
    caloriesPerServing: 430,
    prepTimeMinutes: 10,
    ingredients: [
      RecipeIngredient(name: 'Zabpehely', amount: 60, unit: 'g'),
      RecipeIngredient(name: 'Tej vagy növényi ital', amount: 200, unit: 'ml'),
      RecipeIngredient(name: 'Fehérjepor', amount: 25, unit: 'g'),
      RecipeIngredient(name: 'Bogyós gyümölcs', amount: 80, unit: 'g'),
      RecipeIngredient(name: 'Chia mag', amount: 8, unit: 'g'),
    ],
    steps: [
      'A zabpelyhet melegítsd össze a tejjel vagy növényi itallal.',
      'Keverd bele a fehérjeport, majd hagyd pár percig sűrűsödni.',
      'Tálald bogyós gyümölccsel és chia maggal.',
    ],
    allergens: ['glutén', 'tejfehérje'],
  ),
  Recipe(
    id: 'egg_avocado_toast',
    category: RecipeCategory.breakfast,
    name: 'Tojásos avokádós pirítós',
    emoji: '🥑',
    baseServings: 1,
    caloriesPerServing: 520,
    prepTimeMinutes: 12,
    ingredients: [
      RecipeIngredient(name: 'Teljes kiőrlésű kenyér', amount: 80, unit: 'g'),
      RecipeIngredient(name: 'Tojás', amount: 2, unit: 'db'),
      RecipeIngredient(name: 'Avokádó', amount: 70, unit: 'g'),
      RecipeIngredient(name: 'Citromlé', amount: 5, unit: 'ml'),
      RecipeIngredient(name: 'Só, bors', amount: 1, unit: 'csipet'),
    ],
    steps: [
      'Pirítsd meg a kenyeret.',
      'A tojásokat készítsd el főzve, tükörtojásként vagy rántottaként.',
      'Az avokádót törd össze citromlével, sóval és borssal, majd kend a pirítósra.',
      'Tedd rá a tojást és frissen tálald.',
    ],
    allergens: ['glutén', 'tojás'],
  ),
  Recipe(
    id: 'greek_yogurt_crunch',
    category: RecipeCategory.breakfast,
    name: 'Görög joghurtos granola pohár',
    emoji: '🍯',
    baseServings: 1,
    caloriesPerServing: 390,
    prepTimeMinutes: 6,
    ingredients: [
      RecipeIngredient(name: 'Görög joghurt', amount: 200, unit: 'g'),
      RecipeIngredient(name: 'Granola', amount: 35, unit: 'g'),
      RecipeIngredient(name: 'Banán', amount: 80, unit: 'g'),
      RecipeIngredient(name: 'Méz', amount: 8, unit: 'g'),
      RecipeIngredient(name: 'Dió vagy mandula', amount: 10, unit: 'g'),
    ],
    steps: [
      'A joghurtot kanalazd pohárba vagy tálba.',
      'Rétegezd rá a granolát és a szeletelt banánt.',
      'Locsold meg kevés mézzel, majd szórd meg dióval vagy mandulával.',
    ],
    allergens: ['tejfehérje', 'diófélék', 'glutén'],
  ),
  Recipe(
    id: 'cottage_cheese_pancake',
    category: RecipeCategory.breakfast,
    name: 'Túrós zabpalacsinta',
    emoji: '🥞',
    baseServings: 2,
    caloriesPerServing: 360,
    prepTimeMinutes: 18,
    ingredients: [
      RecipeIngredient(name: 'Zabpehelyliszt', amount: 80, unit: 'g'),
      RecipeIngredient(name: 'Túró', amount: 180, unit: 'g'),
      RecipeIngredient(name: 'Tojás', amount: 2, unit: 'db'),
      RecipeIngredient(name: 'Tej', amount: 100, unit: 'ml'),
      RecipeIngredient(name: 'Sütőpor', amount: 4, unit: 'g'),
    ],
    steps: [
      'Keverd simára a hozzávalókat.',
      'Hagyd állni 5 percig, hogy a zab felvegye a nedvességet.',
      'Tapadásmentes serpenyőben süsd ki kisebb palacsintáknak.',
    ],
    allergens: ['tejfehérje', 'tojás', 'glutén'],
  ),
  Recipe(
    id: 'turkey_egg_wrap',
    category: RecipeCategory.breakfast,
    name: 'Pulykás tojásos wrap',
    emoji: '🌯',
    baseServings: 1,
    caloriesPerServing: 470,
    prepTimeMinutes: 12,
    ingredients: [
      RecipeIngredient(name: 'Teljes kiőrlésű tortilla', amount: 60, unit: 'g'),
      RecipeIngredient(name: 'Tojás', amount: 2, unit: 'db'),
      RecipeIngredient(name: 'Pulykamell sonka', amount: 60, unit: 'g'),
      RecipeIngredient(name: 'Light sajt', amount: 25, unit: 'g'),
      RecipeIngredient(name: 'Friss zöldség', amount: 80, unit: 'g'),
    ],
    steps: [
      'Készíts lágy rántottát a tojásból.',
      'Melegítsd át a tortillát, majd tedd rá a sonkát, sajtot és zöldséget.',
      'Add hozzá a tojást, tekerd fel, majd félbevágva tálald.',
    ],
    allergens: ['glutén', 'tojás', 'tejfehérje'],
  ),
  Recipe(
    id: 'overnight_oats_apple',
    category: RecipeCategory.breakfast,
    name: 'Almás fahéjas overnight oats',
    emoji: '🍎',
    baseServings: 1,
    caloriesPerServing: 410,
    prepTimeMinutes: 8,
    ingredients: [
      RecipeIngredient(name: 'Zabpehely', amount: 55, unit: 'g'),
      RecipeIngredient(name: 'Joghurt', amount: 150, unit: 'g'),
      RecipeIngredient(name: 'Tej vagy növényi ital', amount: 80, unit: 'ml'),
      RecipeIngredient(name: 'Alma', amount: 120, unit: 'g'),
      RecipeIngredient(name: 'Fahéj', amount: 2, unit: 'g'),
    ],
    steps: [
      'Keverd össze a zabot, joghurtot, folyadékot és fahéjat.',
      'Reszeld vagy kockázd bele az almát.',
      'Tedd hűtőbe éjszakára, reggel keverd át és fogyaszd.',
    ],
    allergens: ['glutén', 'tejfehérje'],
  ),
  Recipe(
    id: 'salmon_cream_cheese_bagel',
    category: RecipeCategory.breakfast,
    name: 'Lazacos krémsajtos bagel',
    emoji: '🥯',
    baseServings: 1,
    caloriesPerServing: 560,
    prepTimeMinutes: 8,
    ingredients: [
      RecipeIngredient(name: 'Bagel', amount: 90, unit: 'g'),
      RecipeIngredient(name: 'Krémsajt', amount: 35, unit: 'g'),
      RecipeIngredient(name: 'Füstölt lazac', amount: 60, unit: 'g'),
      RecipeIngredient(name: 'Uborka', amount: 60, unit: 'g'),
      RecipeIngredient(name: 'Citromlé', amount: 5, unit: 'ml'),
    ],
    steps: [
      'Vágd félbe és pirítsd meg a bagelt.',
      'Kend meg krémsajttal, majd tedd rá a lazacot és uborkát.',
      'Kevés citromlével frissítsd, majd azonnal tálald.',
    ],
    allergens: ['glutén', 'tejfehérje', 'hal'],
  ),
  Recipe(
    id: 'veggie_omelette',
    category: RecipeCategory.breakfast,
    name: 'Zöldséges omlett',
    emoji: '🍳',
    baseServings: 1,
    caloriesPerServing: 340,
    prepTimeMinutes: 14,
    ingredients: [
      RecipeIngredient(name: 'Tojás', amount: 3, unit: 'db'),
      RecipeIngredient(name: 'Paprika', amount: 60, unit: 'g'),
      RecipeIngredient(name: 'Paradicsom', amount: 80, unit: 'g'),
      RecipeIngredient(name: 'Spenót', amount: 40, unit: 'g'),
      RecipeIngredient(name: 'Olívaolaj', amount: 5, unit: 'ml'),
    ],
    steps: [
      'A zöldségeket vágd kisebb darabokra.',
      'Kevés olajon párold át őket, majd öntsd rá a felvert tojást.',
      'Lassú tűzön süsd készre, amíg a közepe is megszilárdul.',
    ],
    allergens: ['tojás'],
  ),
  Recipe(
    id: 'banana_peanut_smoothie',
    category: RecipeCategory.breakfast,
    name: 'Banános mogyoróvajas smoothie',
    emoji: '🥤',
    isVegan: true,
    baseServings: 1,
    caloriesPerServing: 455,
    prepTimeMinutes: 5,
    ingredients: [
      RecipeIngredient(name: 'Banán', amount: 120, unit: 'g'),
      RecipeIngredient(name: 'Tej vagy növényi ital', amount: 250, unit: 'ml'),
      RecipeIngredient(name: 'Mogyoróvaj', amount: 22, unit: 'g'),
      RecipeIngredient(name: 'Zabpehely', amount: 25, unit: 'g'),
      RecipeIngredient(name: 'Fehérjepor', amount: 20, unit: 'g'),
    ],
    steps: [
      'Minden hozzávalót tegyél turmixgépbe.',
      'Turmixold krémesre 30-60 másodperc alatt.',
      'Ha sűrűbb állagot szeretnél, adj hozzá jeget vagy kevesebb folyadékot.',
    ],
    allergens: ['földimogyoró', 'tejfehérje', 'glutén'],
  ),
  Recipe(
    id: 'cottage_cheese_bowl',
    category: RecipeCategory.breakfast,
    name: 'Sós cottage cheese tál',
    emoji: '🥒',
    baseServings: 1,
    caloriesPerServing: 365,
    prepTimeMinutes: 7,
    ingredients: [
      RecipeIngredient(name: 'Cottage cheese', amount: 200, unit: 'g'),
      RecipeIngredient(name: 'Teljes kiőrlésű kenyér', amount: 60, unit: 'g'),
      RecipeIngredient(name: 'Uborka', amount: 100, unit: 'g'),
      RecipeIngredient(name: 'Paradicsom', amount: 100, unit: 'g'),
      RecipeIngredient(name: 'Tökmag', amount: 12, unit: 'g'),
    ],
    steps: [
      'A cottage cheese-t kanalazd tálba.',
      'Add mellé a feldarabolt zöldségeket és a kenyeret.',
      'Szórd meg tökmaggal, majd ízlés szerint sózd, borsozd.',
    ],
    allergens: ['tejfehérje', 'glutén'],
  ),
  Recipe(
    id: 'shakshuka_breakfast_bowl',
    category: RecipeCategory.breakfast,
    name: 'Shakshuka reggeli tál',
    emoji: '🍳',
    baseServings: 1,
    caloriesPerServing: 430,
    prepTimeMinutes: 22,
    ingredients: [
      RecipeIngredient(name: 'Tojás', amount: 2, unit: 'db'),
      RecipeIngredient(name: 'Paradicsomszósz', amount: 180, unit: 'g'),
      RecipeIngredient(name: 'Paprika', amount: 90, unit: 'g'),
      RecipeIngredient(name: 'Spenót', amount: 45, unit: 'g'),
      RecipeIngredient(name: 'Feta sajt', amount: 35, unit: 'g'),
    ],
    steps: [
      'A zöldségeket vágd kisebb darabokra.',
      'Kevés olajon párold át őket, majd öntsd rá a felvert tojást.',
      'Add hozzá a paradicsomszószt, majd főzd össze.',
      'Morzsold rá a fetát, és frissen tálald.',
    ],
    allergens: ['tojás', 'tejfehérje'],
  ),
  Recipe(
    id: 'quinoa_yogurt_breakfast',
    category: RecipeCategory.breakfast,
    name: 'Quinoás joghurtos reggeli',
    emoji: '🥣',
    baseServings: 1,
    caloriesPerServing: 410,
    prepTimeMinutes: 14,
    ingredients: [
      RecipeIngredient(name: 'Quinoa', amount: 55, unit: 'g'),
      RecipeIngredient(name: 'Görög joghurt', amount: 170, unit: 'g'),
      RecipeIngredient(name: 'Bogyós gyümölcs', amount: 85, unit: 'g'),
      RecipeIngredient(name: 'Méz', amount: 8, unit: 'g'),
      RecipeIngredient(name: 'Mandula', amount: 10, unit: 'g'),
    ],
    steps: [
      'A quinoát főzd meg.',
      'A joghurtot kanalazd pohárba vagy tálba.',
      'Tálald bogyós gyümölccsel.',
      'Locsold meg kevés mézzel, majd szórd meg mandulával.',
    ],
    allergens: ['tejfehérje', 'diófélék'],
  ),
  Recipe(
    id: 'savory_tuna_toast',
    category: RecipeCategory.breakfast,
    name: 'Tonhalas reggeli pirítós',
    emoji: '🍞',
    baseServings: 1,
    caloriesPerServing: 455,
    prepTimeMinutes: 10,
    ingredients: [
      RecipeIngredient(name: 'Teljes kiőrlésű kenyér', amount: 75, unit: 'g'),
      RecipeIngredient(name: 'Tonhal', amount: 90, unit: 'g'),
      RecipeIngredient(name: 'Görög joghurt', amount: 45, unit: 'g'),
      RecipeIngredient(name: 'Uborka', amount: 70, unit: 'g'),
      RecipeIngredient(name: 'Citromlé', amount: 5, unit: 'ml'),
    ],
    steps: [
      'Pirítsd meg a kenyeret.',
      'A tonhalat keverd össze joghurttal.',
      'A zöldségeket vágd fel.',
      'Kevés citromlével frissítsd, majd azonnal tálald.',
    ],
    allergens: ['glutén', 'hal', 'tejfehérje'],
  ),
  Recipe(
    id: 'apple_cottage_baked_oats',
    category: RecipeCategory.breakfast,
    name: 'Almás túrós sült zab',
    emoji: '🍎',
    baseServings: 2,
    caloriesPerServing: 385,
    prepTimeMinutes: 28,
    ingredients: [
      RecipeIngredient(name: 'Zabpehely', amount: 90, unit: 'g'),
      RecipeIngredient(name: 'Túró', amount: 180, unit: 'g'),
      RecipeIngredient(name: 'Alma', amount: 160, unit: 'g'),
      RecipeIngredient(name: 'Tojás', amount: 1, unit: 'db'),
      RecipeIngredient(name: 'Fahéj', amount: 3, unit: 'g'),
    ],
    steps: [
      'Reszeld vagy kockázd bele az almát.',
      'Keverd simára a hozzávalókat.',
      'Hagyd állni 5 percig, hogy a zab felvegye a nedvességet.',
      'Tapadásmentes serpenyőben süsd ki kisebb palacsintáknak.',
    ],
    allergens: ['glutén', 'tejfehérje', 'tojás'],
  ),
  Recipe(
    id: 'egg_rice_breakfast_pan',
    category: RecipeCategory.breakfast,
    name: 'Tojásos rizses reggeli serpenyő',
    emoji: '🍚',
    baseServings: 1,
    caloriesPerServing: 475,
    prepTimeMinutes: 16,
    ingredients: [
      RecipeIngredient(name: 'Főtt rizs', amount: 210, unit: 'g'),
      RecipeIngredient(name: 'Tojás', amount: 2, unit: 'db'),
      RecipeIngredient(name: 'Zöldborsó', amount: 70, unit: 'g'),
      RecipeIngredient(name: 'Répa', amount: 70, unit: 'g'),
      RecipeIngredient(name: 'Szójaszósz', amount: 12, unit: 'ml'),
    ],
    steps: [
      'A zöldségeket vágd kisebb darabokra.',
      'A zöldségeket pirítsd át.',
      'Add hozzá a rizst és a felvert tojást.',
      'Szójaszósszal ízesítsd, majd süsd össze.',
    ],
    allergens: ['tojás', 'szója'],
  ),
  Recipe(
    id: 'salmon_omelette_plate',
    category: RecipeCategory.breakfast,
    name: 'Lazacos spenótos omlett tányér',
    emoji: '🍳',
    baseServings: 1,
    caloriesPerServing: 500,
    prepTimeMinutes: 15,
    ingredients: [
      RecipeIngredient(name: 'Tojás', amount: 3, unit: 'db'),
      RecipeIngredient(name: 'Füstölt lazac', amount: 55, unit: 'g'),
      RecipeIngredient(name: 'Spenót', amount: 55, unit: 'g'),
      RecipeIngredient(name: 'Krémsajt', amount: 25, unit: 'g'),
      RecipeIngredient(name: 'Uborka', amount: 80, unit: 'g'),
    ],
    steps: [
      'A tojásokat verd fel.',
      'Keverd össze spenóttal és paradicsommal.',
      'Serpenyőben süsd össze sonkával, sajttal és spenóttal.',
      'Kend meg krémsajttal, majd tedd rá a lazacot és uborkát.',
    ],
    allergens: ['tojás', 'tejfehérje', 'hal'],
  ),
  Recipe(
    id: 'hummus_egg_pita',
    category: RecipeCategory.breakfast,
    name: 'Hummuszos tojásos pita',
    emoji: '🫓',
    baseServings: 1,
    caloriesPerServing: 490,
    prepTimeMinutes: 13,
    ingredients: [
      RecipeIngredient(name: 'Teljes kiőrlésű pita', amount: 70, unit: 'g'),
      RecipeIngredient(name: 'Hummusz', amount: 60, unit: 'g'),
      RecipeIngredient(name: 'Tojás', amount: 2, unit: 'db'),
      RecipeIngredient(name: 'Saláta', amount: 45, unit: 'g'),
      RecipeIngredient(name: 'Paprika', amount: 70, unit: 'g'),
    ],
    steps: [
      'A tojásokat főzd meg.',
      'A zöldségeket vágd fel.',
      'A pitát kend meg hummusszal.',
      'Tekerd fel és vágd félbe.',
    ],
    allergens: ['glutén', 'tojás', 'szezám'],
  ),
  Recipe(
    id: 'bulgur_breakfast_feta',
    category: RecipeCategory.breakfast,
    name: 'Fetás bulgur reggeli tál',
    emoji: '🥗',
    baseServings: 1,
    caloriesPerServing: 445,
    prepTimeMinutes: 18,
    ingredients: [
      RecipeIngredient(name: 'Bulgur', amount: 70, unit: 'g'),
      RecipeIngredient(name: 'Feta sajt', amount: 55, unit: 'g'),
      RecipeIngredient(name: 'Paradicsom', amount: 120, unit: 'g'),
      RecipeIngredient(name: 'Uborka', amount: 100, unit: 'g'),
      RecipeIngredient(name: 'Olívaolaj', amount: 8, unit: 'ml'),
    ],
    steps: [
      'A bulgurt főzd meg.',
      'A zöldségeket vágd kockára.',
      'Keverd össze a lencsével és morzsolt fetával.',
      'Locsold meg olívaolajjal, majd hűtve vagy frissen tálald.',
    ],
    allergens: ['glutén', 'tejfehérje'],
  ),
  Recipe(
    id: 'cocoa_chia_oat_cup',
    category: RecipeCategory.breakfast,
    name: 'Kakaós chia zabpohár',
    emoji: '🍫',
    isVegan: true,
    baseServings: 1,
    caloriesPerServing: 420,
    prepTimeMinutes: 8,
    ingredients: [
      RecipeIngredient(name: 'Zabpehely', amount: 55, unit: 'g'),
      RecipeIngredient(name: 'Tej vagy növényi ital', amount: 180, unit: 'ml'),
      RecipeIngredient(name: 'Chia mag', amount: 12, unit: 'g'),
      RecipeIngredient(name: 'Kakaópor', amount: 8, unit: 'g'),
      RecipeIngredient(name: 'Juharszirup', amount: 10, unit: 'g'),
    ],
    steps: [
      'Keverd össze a zabot, tejet vagy növényi italt, chia magot és kakaóport.',
      'Keverd hozzá a juharszirupot, majd hagyd pár percig sűrűsödni.',
      'Tedd hűtőbe éjszakára, reggel keverd át és fogyaszd.',
    ],
    allergens: ['glutén'],
  ),
  Recipe(
    id: 'turkey_cottage_breakfast_box',
    category: RecipeCategory.breakfast,
    name: 'Pulykás cottage reggeli doboz',
    emoji: '🥒',
    baseServings: 1,
    caloriesPerServing: 390,
    prepTimeMinutes: 9,
    ingredients: [
      RecipeIngredient(name: 'Cottage cheese', amount: 170, unit: 'g'),
      RecipeIngredient(name: 'Pulykasonka', amount: 65, unit: 'g'),
      RecipeIngredient(name: 'Teljes kiőrlésű abonett', amount: 30, unit: 'g'),
      RecipeIngredient(name: 'Paradicsom', amount: 100, unit: 'g'),
      RecipeIngredient(name: 'Tökmag', amount: 8, unit: 'g'),
    ],
    steps: [
      'A cottage cheese-t kanalazd tálba.',
      'A zöldségeket vágd fel.',
      'Add mellé a feldarabolt zöldségeket és a kenyeret.',
      'Szórd meg tökmaggal, majd ízlés szerint sózd, borsozd.',
    ],
    allergens: ['tejfehérje', 'glutén'],
  ),
];

const lunchRecipes = [
  Recipe(
    id: 'chicken_rice_bowl',
    category: RecipeCategory.lunch,
    name: 'Csirkés rizses fit bowl',
    emoji: '🍗',
    baseServings: 2,
    caloriesPerServing: 610,
    prepTimeMinutes: 35,
    ingredients: [
      RecipeIngredient(name: 'Csirkemell', amount: 320, unit: 'g'),
      RecipeIngredient(name: 'Rizs', amount: 160, unit: 'g'),
      RecipeIngredient(name: 'Brokkoli', amount: 240, unit: 'g'),
      RecipeIngredient(name: 'Olívaolaj', amount: 12, unit: 'ml'),
      RecipeIngredient(name: 'Fűszerkeverék', amount: 6, unit: 'g'),
    ],
    steps: [
      'A rizst főzd meg, a csirkemellet fűszerezd és süsd készre.',
      'A brokkolit párold roppanósra.',
      'Oszd dobozokra a rizst, csirkét és brokkolit.',
    ],
    allergens: ['nincs kiemelt allergén'],
  ),
  Recipe(
    id: 'turkey_bolognese_pasta',
    category: RecipeCategory.lunch,
    name: 'Pulykás bolognai tészta',
    emoji: '🍝',
    baseServings: 3,
    caloriesPerServing: 560,
    prepTimeMinutes: 35,
    ingredients: [
      RecipeIngredient(name: 'Darált pulykahús', amount: 360, unit: 'g'),
      RecipeIngredient(name: 'Teljes kiőrlésű tészta', amount: 240, unit: 'g'),
      RecipeIngredient(name: 'Paradicsomszósz', amount: 360, unit: 'g'),
      RecipeIngredient(name: 'Reszelt sajt', amount: 45, unit: 'g'),
      RecipeIngredient(name: 'Olívaolaj', amount: 10, unit: 'ml'),
    ],
    steps: [
      'A pulykahúst kevés olajon pirítsd le.',
      'Add hozzá a paradicsomszószt, majd főzd össze.',
      'Keverd össze a kifőtt tésztával, és adagold sajttal megszórva.',
    ],
    allergens: ['glutén', 'tejfehérje'],
  ),
  Recipe(
    id: 'salmon_potato_plate',
    category: RecipeCategory.lunch,
    name: 'Lazacos burgonyás ebéd',
    emoji: '🐟',
    baseServings: 2,
    caloriesPerServing: 640,
    prepTimeMinutes: 30,
    ingredients: [
      RecipeIngredient(name: 'Lazacfilé', amount: 300, unit: 'g'),
      RecipeIngredient(name: 'Burgonya', amount: 500, unit: 'g'),
      RecipeIngredient(name: 'Zöldsaláta', amount: 160, unit: 'g'),
      RecipeIngredient(name: 'Joghurtos öntet', amount: 80, unit: 'g'),
      RecipeIngredient(name: 'Citromlé', amount: 10, unit: 'ml'),
    ],
    steps: [
      'A burgonyát főzd vagy süsd puhára.',
      'A lazacot sózd, borsozd, majd süsd készre.',
      'Tálald salátával és joghurtos öntettel.',
    ],
    allergens: ['hal', 'tejfehérje'],
  ),
  Recipe(
    id: 'beef_bulgur_pan',
    category: RecipeCategory.lunch,
    name: 'Marhahúsos bulgur serpenyő',
    emoji: '🥘',
    baseServings: 3,
    caloriesPerServing: 590,
    prepTimeMinutes: 32,
    ingredients: [
      RecipeIngredient(name: 'Sovány marhahús', amount: 390, unit: 'g'),
      RecipeIngredient(name: 'Bulgur', amount: 210, unit: 'g'),
      RecipeIngredient(name: 'Paprika', amount: 180, unit: 'g'),
      RecipeIngredient(name: 'Cukkini', amount: 220, unit: 'g'),
      RecipeIngredient(name: 'Paradicsompüré', amount: 60, unit: 'g'),
    ],
    steps: [
      'A bulgurt főzd meg.',
      'A marhahúst pirítsd le, majd add hozzá a zöldségeket.',
      'Keverd hozzá a bulgurt és a paradicsompürét, majd főzd össze.',
    ],
    allergens: ['glutén'],
  ),
  Recipe(
    id: 'tofu_noodle_box',
    category: RecipeCategory.lunch,
    name: 'Tofus zöldséges noodle box',
    emoji: '🍜',
    isVegan: true,
    baseServings: 2,
    caloriesPerServing: 520,
    prepTimeMinutes: 25,
    ingredients: [
      RecipeIngredient(name: 'Tofu', amount: 300, unit: 'g'),
      RecipeIngredient(name: 'Rizstészta', amount: 160, unit: 'g'),
      RecipeIngredient(name: 'Wok zöldség', amount: 300, unit: 'g'),
      RecipeIngredient(name: 'Szójaszósz', amount: 30, unit: 'ml'),
      RecipeIngredient(name: 'Szezámmag', amount: 12, unit: 'g'),
    ],
    steps: [
      'A rizstésztát áztasd vagy főzd meg a csomagolás szerint.',
      'A tofut kockázd fel és pirítsd meg.',
      'Forgasd össze a zöldségekkel, tésztával és szójaszósszal.',
    ],
    allergens: ['szója', 'szezám'],
  ),
  Recipe(
    id: 'chickpea_curry',
    category: RecipeCategory.lunch,
    name: 'Csicseriborsó curry rizzsel',
    emoji: '🍛',
    isVegan: true,
    baseServings: 3,
    caloriesPerServing: 575,
    prepTimeMinutes: 30,
    ingredients: [
      RecipeIngredient(name: 'Csicseriborsó', amount: 480, unit: 'g'),
      RecipeIngredient(name: 'Rizs', amount: 210, unit: 'g'),
      RecipeIngredient(name: 'Kókusztej', amount: 250, unit: 'ml'),
      RecipeIngredient(name: 'Paradicsom', amount: 250, unit: 'g'),
      RecipeIngredient(name: 'Curry fűszer', amount: 8, unit: 'g'),
    ],
    steps: [
      'A rizst főzd meg.',
      'A csicseriborsót főzd össze paradicsommal, kókusztejjel és curryvel.',
      'Tálald a curry alapot rizzsel.',
    ],
    allergens: ['nincs kiemelt allergén'],
  ),
  Recipe(
    id: 'pork_tenderloin_couscous',
    category: RecipeCategory.lunch,
    name: 'Sertésszűz kuszkusszal',
    emoji: '🥩',
    baseServings: 2,
    caloriesPerServing: 620,
    prepTimeMinutes: 28,
    ingredients: [
      RecipeIngredient(name: 'Sertésszűz', amount: 320, unit: 'g'),
      RecipeIngredient(name: 'Kuszkusz', amount: 160, unit: 'g'),
      RecipeIngredient(name: 'Zöldbab', amount: 240, unit: 'g'),
      RecipeIngredient(name: 'Olívaolaj', amount: 12, unit: 'ml'),
      RecipeIngredient(name: 'Mustár', amount: 15, unit: 'g'),
    ],
    steps: [
      'A kuszkuszt forró vízzel párold meg.',
      'A sertésszüzet fűszerezd és süsd szeletekre.',
      'Tálald zöldbabbal és kevés mustáros szósszal.',
    ],
    allergens: ['glutén', 'mustár'],
  ),
  Recipe(
    id: 'lentil_feta_salad',
    category: RecipeCategory.lunch,
    name: 'Lencsés feta saláta',
    emoji: '🥗',
    baseServings: 2,
    caloriesPerServing: 480,
    prepTimeMinutes: 18,
    ingredients: [
      RecipeIngredient(name: 'Főtt lencse', amount: 360, unit: 'g'),
      RecipeIngredient(name: 'Feta sajt', amount: 100, unit: 'g'),
      RecipeIngredient(name: 'Uborka', amount: 160, unit: 'g'),
      RecipeIngredient(name: 'Paradicsom', amount: 180, unit: 'g'),
      RecipeIngredient(name: 'Olívaolaj', amount: 14, unit: 'ml'),
    ],
    steps: [
      'A zöldségeket vágd kockára.',
      'Keverd össze a lencsével és morzsolt fetával.',
      'Locsold meg olívaolajjal, majd hűtve vagy frissen tálald.',
    ],
    allergens: ['tejfehérje'],
  ),
  Recipe(
    id: 'chicken_pita_plate',
    category: RecipeCategory.lunch,
    name: 'Csirkés pita tál',
    emoji: '🫓',
    baseServings: 2,
    caloriesPerServing: 585,
    prepTimeMinutes: 25,
    ingredients: [
      RecipeIngredient(name: 'Csirkemell', amount: 300, unit: 'g'),
      RecipeIngredient(name: 'Teljes kiőrlésű pita', amount: 140, unit: 'g'),
      RecipeIngredient(name: 'Joghurt', amount: 120, unit: 'g'),
      RecipeIngredient(name: 'Saláta mix', amount: 180, unit: 'g'),
      RecipeIngredient(name: 'Fűszerkeverék', amount: 6, unit: 'g'),
    ],
    steps: [
      'A csirkét fűszerezd és süsd készre.',
      'A joghurtból készíts egyszerű öntetet.',
      'Tálald pitával, salátával és joghurtos szósszal.',
    ],
    allergens: ['glutén', 'tejfehérje'],
  ),
  Recipe(
    id: 'tuna_sweetcorn_pasta',
    category: RecipeCategory.lunch,
    name: 'Tonhalas kukoricás tésztasaláta',
    emoji: '🥫',
    baseServings: 3,
    caloriesPerServing: 515,
    prepTimeMinutes: 20,
    ingredients: [
      RecipeIngredient(name: 'Tészta', amount: 240, unit: 'g'),
      RecipeIngredient(name: 'Tonhal', amount: 240, unit: 'g'),
      RecipeIngredient(name: 'Kukorica', amount: 180, unit: 'g'),
      RecipeIngredient(name: 'Görög joghurt', amount: 150, unit: 'g'),
      RecipeIngredient(name: 'Lilahagyma', amount: 60, unit: 'g'),
    ],
    steps: [
      'A tésztát főzd meg és hűtsd vissza.',
      'Keverd össze tonhallal, kukoricával és joghurttal.',
      'Add hozzá a hagymát, majd adagold dobozokba.',
    ],
    allergens: ['glutén', 'hal', 'tejfehérje'],
  ),
  Recipe(
    id: 'mediterran_turkey_bulgur',
    category: RecipeCategory.lunch,
    name: 'Mediterrán pulykás bulgur',
    emoji: '🍲',
    baseServings: 2,
    caloriesPerServing: 585,
    prepTimeMinutes: 30,
    ingredients: [
      RecipeIngredient(name: 'Darált pulykahús', amount: 320, unit: 'g'),
      RecipeIngredient(name: 'Bulgur', amount: 180, unit: 'g'),
      RecipeIngredient(name: 'Paradicsompüré', amount: 70, unit: 'g'),
      RecipeIngredient(name: 'Cukkini', amount: 220, unit: 'g'),
      RecipeIngredient(name: 'Feta sajt', amount: 60, unit: 'g'),
    ],
    steps: [
      'A pulykahúst kevés olajon pirítsd le.',
      'A bulgurt főzd meg.',
      'Keverd hozzá a bulgurt és a paradicsompürét, majd főzd össze.',
      'Morzsold rá a fetát, és tálald a zöldséges bulgurral.',
    ],
    allergens: ['glutén', 'tejfehérje'],
  ),
  Recipe(
    id: 'shrimp_rice_noodle_lunch',
    category: RecipeCategory.lunch,
    name: 'Garnélás rizstészta wok',
    emoji: '🍤',
    baseServings: 2,
    caloriesPerServing: 540,
    prepTimeMinutes: 24,
    ingredients: [
      RecipeIngredient(name: 'Garnéla', amount: 280, unit: 'g'),
      RecipeIngredient(name: 'Rizstészta', amount: 170, unit: 'g'),
      RecipeIngredient(name: 'Wok zöldség', amount: 320, unit: 'g'),
      RecipeIngredient(name: 'Szójaszósz', amount: 28, unit: 'ml'),
      RecipeIngredient(name: 'Szezámmag', amount: 10, unit: 'g'),
    ],
    steps: [
      'A rizstésztát áztasd vagy főzd meg a csomagolás szerint.',
      'A garnélát kevés olajon pirítsd készre.',
      'A zöldségeket pirítsd át.',
      'Forgasd össze a zöldségekkel, tésztával és szójaszósszal.',
    ],
    allergens: ['rákfélék', 'szója', 'szezám'],
  ),
  Recipe(
    id: 'pork_potato_mustard_plate',
    category: RecipeCategory.lunch,
    name: 'Mustáros sertésszűz burgonyával',
    emoji: '🥔',
    baseServings: 2,
    caloriesPerServing: 620,
    prepTimeMinutes: 32,
    ingredients: [
      RecipeIngredient(name: 'Sertésszűz', amount: 320, unit: 'g'),
      RecipeIngredient(name: 'Burgonya', amount: 460, unit: 'g'),
      RecipeIngredient(name: 'Zöldbab', amount: 220, unit: 'g'),
      RecipeIngredient(name: 'Mustár', amount: 18, unit: 'g'),
      RecipeIngredient(name: 'Joghurtos öntet', amount: 55, unit: 'g'),
    ],
    steps: [
      'A sertésszüzet fűszerezd és süsd szeletekre.',
      'A burgonyát főzd vagy süsd puhára.',
      'A zöldségeket pirítsd át.',
      'Tálald zöldbabbal és kevés mustáros szósszal.',
    ],
    allergens: ['mustár', 'tejfehérje'],
  ),
  Recipe(
    id: 'veggie_lentil_rice_pot',
    category: RecipeCategory.lunch,
    name: 'Lencsés zöldséges rizses egytál',
    emoji: '🍛',
    isVegan: true,
    baseServings: 3,
    caloriesPerServing: 505,
    prepTimeMinutes: 28,
    ingredients: [
      RecipeIngredient(name: 'Főtt lencse', amount: 420, unit: 'g'),
      RecipeIngredient(name: 'Rizs', amount: 210, unit: 'g'),
      RecipeIngredient(name: 'Paradicsom', amount: 260, unit: 'g'),
      RecipeIngredient(name: 'Répa', amount: 160, unit: 'g'),
      RecipeIngredient(name: 'Curry fűszer', amount: 7, unit: 'g'),
    ],
    steps: [
      'A rizst főzd meg.',
      'A zöldségeket vágd kockára.',
      'A zöldségeket pirítsd át.',
      'Főzd össze sűrű raguvá.',
    ],
    allergens: ['nincs kiemelt allergén'],
  ),
  Recipe(
    id: 'greek_salmon_quinoa',
    category: RecipeCategory.lunch,
    name: 'Görög lazacos quinoa tál',
    emoji: '🐟',
    baseServings: 2,
    caloriesPerServing: 650,
    prepTimeMinutes: 26,
    ingredients: [
      RecipeIngredient(name: 'Lazacfilé', amount: 300, unit: 'g'),
      RecipeIngredient(name: 'Quinoa', amount: 150, unit: 'g'),
      RecipeIngredient(name: 'Uborka', amount: 150, unit: 'g'),
      RecipeIngredient(name: 'Paradicsom', amount: 160, unit: 'g'),
      RecipeIngredient(name: 'Tzatziki', amount: 110, unit: 'g'),
    ],
    steps: [
      'A lazacot sózd, borsozd, majd süsd készre.',
      'A quinoát főzd meg.',
      'A zöldségeket vágd kockára.',
      'Kanalazd mellé a tzatzikit, és tálald a quinoa-zöldség alappal.',
    ],
    allergens: ['hal', 'tejfehérje'],
  ),
  Recipe(
    id: 'beef_pita_lunch',
    category: RecipeCategory.lunch,
    name: 'Marhahúsos pita ebéd',
    emoji: '🥙',
    baseServings: 2,
    caloriesPerServing: 610,
    prepTimeMinutes: 25,
    ingredients: [
      RecipeIngredient(name: 'Sovány marhahús', amount: 300, unit: 'g'),
      RecipeIngredient(name: 'Teljes kiőrlésű pita', amount: 150, unit: 'g'),
      RecipeIngredient(name: 'Saláta mix', amount: 170, unit: 'g'),
      RecipeIngredient(name: 'Joghurt', amount: 100, unit: 'g'),
      RecipeIngredient(name: 'Fűszerkeverék', amount: 7, unit: 'g'),
    ],
    steps: [
      'A marhahúst pirítsd le, majd add hozzá a zöldségeket.',
      'A joghurtból készíts egyszerű öntetet.',
      'A zöldségeket rendezd tálba.',
      'Tálald pitával, salátával és joghurtos szósszal.',
    ],
    allergens: ['glutén', 'tejfehérje'],
  ),
  Recipe(
    id: 'tofu_chickpea_curry',
    category: RecipeCategory.lunch,
    name: 'Tofus csicseriborsó curry',
    emoji: '🍛',
    isVegan: true,
    baseServings: 3,
    caloriesPerServing: 560,
    prepTimeMinutes: 30,
    ingredients: [
      RecipeIngredient(name: 'Tofu', amount: 280, unit: 'g'),
      RecipeIngredient(name: 'Csicseriborsó', amount: 420, unit: 'g'),
      RecipeIngredient(name: 'Kókusztej', amount: 260, unit: 'ml'),
      RecipeIngredient(name: 'Paradicsom', amount: 240, unit: 'g'),
      RecipeIngredient(name: 'Curry fűszer', amount: 9, unit: 'g'),
    ],
    steps: [
      'A tofut kockázd fel és pirítsd meg.',
      'A csicseriborsót főzd össze paradicsommal, kókusztejjel és curryvel.',
      'Főzd össze sűrű raguvá.',
      'Tálald a curry alapot rizzsel.',
    ],
    allergens: ['szója'],
  ),
  Recipe(
    id: 'chicken_couscous_box',
    category: RecipeCategory.lunch,
    name: 'Csirkés kuszkuszos doboz',
    emoji: '🍱',
    baseServings: 2,
    caloriesPerServing: 565,
    prepTimeMinutes: 22,
    ingredients: [
      RecipeIngredient(name: 'Csirkemell', amount: 300, unit: 'g'),
      RecipeIngredient(name: 'Kuszkusz', amount: 170, unit: 'g'),
      RecipeIngredient(name: 'Brokkoli', amount: 220, unit: 'g'),
      RecipeIngredient(name: 'Joghurtos öntet', amount: 70, unit: 'g'),
      RecipeIngredient(name: 'Fűszerkeverék', amount: 7, unit: 'g'),
    ],
    steps: [
      'A csirkemellet süsd készre és szeleteld fel.',
      'A kuszkuszt forró vízzel párold meg.',
      'A brokkolit párold roppanósra.',
      'Oszd dobozokra a kuszkuszt, csirkét és brokkolit.',
    ],
    allergens: ['glutén', 'tejfehérje'],
  ),
  Recipe(
    id: 'stuffed_zucchini_turkey',
    category: RecipeCategory.lunch,
    name: 'Pulykával töltött cukkini',
    emoji: '🥒',
    baseServings: 2,
    caloriesPerServing: 520,
    prepTimeMinutes: 35,
    ingredients: [
      RecipeIngredient(name: 'Cukkini', amount: 520, unit: 'g'),
      RecipeIngredient(name: 'Darált pulykahús', amount: 330, unit: 'g'),
      RecipeIngredient(name: 'Főtt rizs', amount: 180, unit: 'g'),
      RecipeIngredient(name: 'Paradicsomszósz', amount: 260, unit: 'g'),
      RecipeIngredient(name: 'Reszelt sajt', amount: 45, unit: 'g'),
    ],
    steps: [
      'A zöldségeket vágd fel.',
      'A pulykahúst kevés olajon pirítsd le.',
      'Töltsd meg húsos-rizses keverékkel.',
      'Paradicsomszósszal és sajttal süsd készre.',
    ],
    allergens: ['tejfehérje'],
  ),
  Recipe(
    id: 'tuna_bean_potato_salad',
    category: RecipeCategory.lunch,
    name: 'Tonhalas babos burgonyasaláta',
    emoji: '🥗',
    baseServings: 2,
    caloriesPerServing: 575,
    prepTimeMinutes: 24,
    ingredients: [
      RecipeIngredient(name: 'Tonhal', amount: 200, unit: 'g'),
      RecipeIngredient(name: 'Burgonya', amount: 360, unit: 'g'),
      RecipeIngredient(name: 'Vörösbab', amount: 260, unit: 'g'),
      RecipeIngredient(name: 'Uborka', amount: 130, unit: 'g'),
      RecipeIngredient(name: 'Joghurtos öntet', amount: 75, unit: 'g'),
    ],
    steps: [
      'A burgonyát főzd vagy süsd puhára.',
      'A zöldségeket vágd kockára.',
      'Keverd össze a tonhalat a babbal, burgonyával és joghurtos öntettel.',
      'Locsold meg olívaolajjal, majd hűtve vagy frissen tálald.',
    ],
    allergens: ['hal', 'tejfehérje'],
  ),
];

const dinnerRecipes = [
  Recipe(
    id: 'light_chicken_salad',
    category: RecipeCategory.dinner,
    name: 'Könnyű csirkés saláta',
    emoji: '🥗',
    baseServings: 1,
    caloriesPerServing: 410,
    prepTimeMinutes: 18,
    ingredients: [
      RecipeIngredient(name: 'Csirkemell', amount: 160, unit: 'g'),
      RecipeIngredient(name: 'Saláta mix', amount: 140, unit: 'g'),
      RecipeIngredient(name: 'Avokádó', amount: 50, unit: 'g'),
      RecipeIngredient(name: 'Paradicsom', amount: 100, unit: 'g'),
      RecipeIngredient(name: 'Joghurtos öntet', amount: 45, unit: 'g'),
    ],
    steps: [
      'A csirkemellet süsd készre és szeleteld fel.',
      'A zöldségeket rendezd tálba.',
      'Tedd rá a csirkét és az öntetet.',
    ],
    allergens: ['tejfehérje'],
  ),
  Recipe(
    id: 'egg_fried_rice_light',
    category: RecipeCategory.dinner,
    name: 'Tojásos zöldséges rizs',
    emoji: '🍚',
    baseServings: 2,
    caloriesPerServing: 455,
    prepTimeMinutes: 20,
    ingredients: [
      RecipeIngredient(name: 'Főtt rizs', amount: 360, unit: 'g'),
      RecipeIngredient(name: 'Tojás', amount: 3, unit: 'db'),
      RecipeIngredient(name: 'Zöldborsó', amount: 120, unit: 'g'),
      RecipeIngredient(name: 'Répa', amount: 100, unit: 'g'),
      RecipeIngredient(name: 'Szójaszósz', amount: 20, unit: 'ml'),
    ],
    steps: [
      'A zöldségeket pirítsd át.',
      'Add hozzá a rizst és a felvert tojást.',
      'Szójaszósszal ízesítsd, majd süsd össze.',
    ],
    allergens: ['tojás', 'szója'],
  ),
  Recipe(
    id: 'turkey_meatballs_zoodles',
    category: RecipeCategory.dinner,
    name: 'Pulykagolyók cukkinispagettivel',
    emoji: '🍝',
    baseServings: 2,
    caloriesPerServing: 430,
    prepTimeMinutes: 32,
    ingredients: [
      RecipeIngredient(name: 'Darált pulykahús', amount: 320, unit: 'g'),
      RecipeIngredient(name: 'Cukkini', amount: 420, unit: 'g'),
      RecipeIngredient(name: 'Paradicsomszósz', amount: 250, unit: 'g'),
      RecipeIngredient(name: 'Tojás', amount: 1, unit: 'db'),
      RecipeIngredient(name: 'Zsemlemorzsa', amount: 25, unit: 'g'),
    ],
    steps: [
      'A pulykahúsból tojással és morzsával formázz golyókat.',
      'Süsd vagy párold készre paradicsomszószban.',
      'Cukkinispagettivel tálald.',
    ],
    allergens: ['tojás', 'glutén'],
  ),
  Recipe(
    id: 'cod_vegetable_tray',
    category: RecipeCategory.dinner,
    name: 'Sült hal zöldségágyon',
    emoji: '🐟',
    baseServings: 2,
    caloriesPerServing: 390,
    prepTimeMinutes: 28,
    ingredients: [
      RecipeIngredient(name: 'Fehér halfilé', amount: 320, unit: 'g'),
      RecipeIngredient(name: 'Cukkini', amount: 200, unit: 'g'),
      RecipeIngredient(name: 'Paprika', amount: 160, unit: 'g'),
      RecipeIngredient(name: 'Lilahagyma', amount: 80, unit: 'g'),
      RecipeIngredient(name: 'Olívaolaj', amount: 12, unit: 'ml'),
    ],
    steps: [
      'A zöldségeket terítsd tepsibe.',
      'Helyezd rá a halfilét, fűszerezd és locsold meg olajjal.',
      'Süsd készre, amíg a hal omlós lesz.',
    ],
    allergens: ['hal'],
  ),
  Recipe(
    id: 'cottage_cheese_veg_plate',
    category: RecipeCategory.dinner,
    name: 'Cottage cheese zöldségtál',
    emoji: '🥒',
    baseServings: 1,
    caloriesPerServing: 350,
    prepTimeMinutes: 8,
    ingredients: [
      RecipeIngredient(name: 'Cottage cheese', amount: 220, unit: 'g'),
      RecipeIngredient(name: 'Uborka', amount: 120, unit: 'g'),
      RecipeIngredient(name: 'Paradicsom', amount: 120, unit: 'g'),
      RecipeIngredient(name: 'Teljes kiőrlésű abonett', amount: 30, unit: 'g'),
      RecipeIngredient(name: 'Tökmag', amount: 10, unit: 'g'),
    ],
    steps: [
      'A zöldségeket vágd fel.',
      'Tálald cottage cheese-zel, abonettel és tökmaggal.',
      'Ízlés szerint sózd, borsozd.',
    ],
    allergens: ['tejfehérje', 'glutén'],
  ),
  Recipe(
    id: 'shrimp_quinoa_bowl',
    category: RecipeCategory.dinner,
    name: 'Garnélás quinoa bowl',
    emoji: '🍤',
    baseServings: 2,
    caloriesPerServing: 485,
    prepTimeMinutes: 24,
    ingredients: [
      RecipeIngredient(name: 'Garnéla', amount: 280, unit: 'g'),
      RecipeIngredient(name: 'Quinoa', amount: 140, unit: 'g'),
      RecipeIngredient(name: 'Spenót', amount: 100, unit: 'g'),
      RecipeIngredient(name: 'Koktélparadicsom', amount: 160, unit: 'g'),
      RecipeIngredient(name: 'Olívaolaj', amount: 10, unit: 'ml'),
    ],
    steps: [
      'A quinoát főzd meg.',
      'A garnélát kevés olajon pirítsd készre.',
      'Keverd össze spenóttal és paradicsommal.',
    ],
    allergens: ['rákfélék'],
  ),
  Recipe(
    id: 'bean_chili_light',
    category: RecipeCategory.dinner,
    name: 'Könnyű babos chili',
    emoji: '🌶️',
    isVegan: true,
    baseServings: 3,
    caloriesPerServing: 440,
    prepTimeMinutes: 30,
    ingredients: [
      RecipeIngredient(name: 'Vörösbab', amount: 420, unit: 'g'),
      RecipeIngredient(name: 'Szójagranulátum', amount: 160, unit: 'g'),
      RecipeIngredient(name: 'Paradicsom', amount: 350, unit: 'g'),
      RecipeIngredient(name: 'Kukorica', amount: 150, unit: 'g'),
      RecipeIngredient(name: 'Chili fűszer', amount: 6, unit: 'g'),
    ],
    steps: [
      'A szójagranulátumot áztasd be, majd pirítsd le.',
      'Add hozzá a babot, kukoricát, paradicsomot és fűszert.',
      'Főzd össze sűrű raguvá.',
    ],
    allergens: ['szója'],
  ),
  Recipe(
    id: 'ham_cheese_omelette',
    category: RecipeCategory.dinner,
    name: 'Sonkás sajtos omlett',
    emoji: '🍳',
    baseServings: 1,
    caloriesPerServing: 420,
    prepTimeMinutes: 12,
    ingredients: [
      RecipeIngredient(name: 'Tojás', amount: 3, unit: 'db'),
      RecipeIngredient(name: 'Pulykasonka', amount: 70, unit: 'g'),
      RecipeIngredient(name: 'Light sajt', amount: 35, unit: 'g'),
      RecipeIngredient(name: 'Spenót', amount: 50, unit: 'g'),
      RecipeIngredient(name: 'Olívaolaj', amount: 5, unit: 'ml'),
    ],
    steps: [
      'A tojásokat verd fel.',
      'Serpenyőben süsd össze sonkával, sajttal és spenóttal.',
      'Hajtsd félbe és frissen tálald.',
    ],
    allergens: ['tojás', 'tejfehérje'],
  ),
  Recipe(
    id: 'stuffed_peppers',
    category: RecipeCategory.dinner,
    name: 'Töltött paprika light módra',
    emoji: '🫑',
    baseServings: 3,
    caloriesPerServing: 470,
    prepTimeMinutes: 42,
    ingredients: [
      RecipeIngredient(name: 'Kaliforniai paprika', amount: 450, unit: 'g'),
      RecipeIngredient(name: 'Darált csirkemell', amount: 360, unit: 'g'),
      RecipeIngredient(name: 'Főtt rizs', amount: 240, unit: 'g'),
      RecipeIngredient(name: 'Paradicsomszósz', amount: 300, unit: 'g'),
      RecipeIngredient(name: 'Reszelt sajt', amount: 60, unit: 'g'),
    ],
    steps: [
      'A paprikákat vágd félbe és magozd ki.',
      'Töltsd meg húsos-rizses keverékkel.',
      'Paradicsomszósszal és sajttal süsd készre.',
    ],
    allergens: ['tejfehérje'],
  ),
  Recipe(
    id: 'greek_chicken_plate',
    category: RecipeCategory.dinner,
    name: 'Görög csirkés tányér',
    emoji: '🫒',
    baseServings: 2,
    caloriesPerServing: 505,
    prepTimeMinutes: 25,
    ingredients: [
      RecipeIngredient(name: 'Csirkemell', amount: 300, unit: 'g'),
      RecipeIngredient(name: 'Uborka', amount: 150, unit: 'g'),
      RecipeIngredient(name: 'Paradicsom', amount: 160, unit: 'g'),
      RecipeIngredient(name: 'Feta sajt', amount: 70, unit: 'g'),
      RecipeIngredient(name: 'Tzatziki', amount: 120, unit: 'g'),
    ],
    steps: [
      'A csirkét fűszerezd és süsd készre.',
      'A zöldségeket vágd fel.',
      'Tálald fetával és tzatzikivel.',
    ],
    allergens: ['tejfehérje'],
  ),
  Recipe(
    id: 'miso_tofu_quinoa_dinner',
    category: RecipeCategory.dinner,
    name: 'Tofus quinoás vacsoratál',
    emoji: '🥢',
    isVegan: true,
    baseServings: 2,
    caloriesPerServing: 455,
    prepTimeMinutes: 24,
    ingredients: [
      RecipeIngredient(name: 'Tofu', amount: 260, unit: 'g'),
      RecipeIngredient(name: 'Quinoa', amount: 130, unit: 'g'),
      RecipeIngredient(name: 'Wok zöldség', amount: 280, unit: 'g'),
      RecipeIngredient(name: 'Szójaszósz', amount: 24, unit: 'ml'),
      RecipeIngredient(name: 'Szezámmag', amount: 10, unit: 'g'),
    ],
    steps: [
      'A quinoát főzd meg.',
      'A tofut kockázd fel és pirítsd meg.',
      'A zöldségeket pirítsd át.',
      'Forgasd össze a zöldségekkel, tésztával és szójaszósszal.',
    ],
    allergens: ['szója', 'szezám'],
  ),
  Recipe(
    id: 'salmon_green_bean_dinner',
    category: RecipeCategory.dinner,
    name: 'Lazacos zöldbabos vacsora',
    emoji: '🐟',
    baseServings: 2,
    caloriesPerServing: 520,
    prepTimeMinutes: 25,
    ingredients: [
      RecipeIngredient(name: 'Lazacfilé', amount: 280, unit: 'g'),
      RecipeIngredient(name: 'Zöldbab', amount: 260, unit: 'g'),
      RecipeIngredient(name: 'Burgonya', amount: 300, unit: 'g'),
      RecipeIngredient(name: 'Citromlé', amount: 10, unit: 'ml'),
      RecipeIngredient(name: 'Olívaolaj', amount: 10, unit: 'ml'),
    ],
    steps: [
      'A lazacot sózd, borsozd, majd süsd készre.',
      'A burgonyát főzd vagy süsd puhára.',
      'A zöldségeket pirítsd át.',
      'Kevés citromlével frissítsd, majd azonnal tálald.',
    ],
    allergens: ['hal'],
  ),
  Recipe(
    id: 'turkey_chili_stuffed_pepper',
    category: RecipeCategory.dinner,
    name: 'Chilis pulykával töltött paprika',
    emoji: '🫑',
    baseServings: 3,
    caloriesPerServing: 470,
    prepTimeMinutes: 36,
    ingredients: [
      RecipeIngredient(name: 'Kaliforniai paprika', amount: 500, unit: 'g'),
      RecipeIngredient(name: 'Darált pulykahús', amount: 330, unit: 'g'),
      RecipeIngredient(name: 'Vörösbab', amount: 260, unit: 'g'),
      RecipeIngredient(name: 'Paradicsomszósz', amount: 280, unit: 'g'),
      RecipeIngredient(name: 'Chili fűszer', amount: 7, unit: 'g'),
    ],
    steps: [
      'A paprikákat vágd félbe és magozd ki.',
      'A pulykahúst kevés olajon pirítsd le.',
      'Add hozzá a babot, paradicsomszószt és fűszert.',
      'Töltsd meg pulykás-babos keverékkel.',
    ],
    allergens: ['nincs kiemelt allergén'],
  ),
  Recipe(
    id: 'shrimp_cottage_salad',
    category: RecipeCategory.dinner,
    name: 'Garnélás cottage saláta',
    emoji: '🍤',
    baseServings: 1,
    caloriesPerServing: 430,
    prepTimeMinutes: 16,
    ingredients: [
      RecipeIngredient(name: 'Garnéla', amount: 160, unit: 'g'),
      RecipeIngredient(name: 'Cottage cheese', amount: 160, unit: 'g'),
      RecipeIngredient(name: 'Saláta mix', amount: 140, unit: 'g'),
      RecipeIngredient(name: 'Koktélparadicsom', amount: 120, unit: 'g'),
      RecipeIngredient(name: 'Olívaolaj', amount: 8, unit: 'ml'),
    ],
    steps: [
      'A garnélát kevés olajon pirítsd készre.',
      'A zöldségeket rendezd tálba.',
      'A cottage cheese-t kanalazd tálba.',
      'Locsold meg olívaolajjal, majd hűtve vagy frissen tálald.',
    ],
    allergens: ['rákfélék', 'tejfehérje'],
  ),
  Recipe(
    id: 'beef_zucchini_rice_dinner',
    category: RecipeCategory.dinner,
    name: 'Marhás cukkinis rizs',
    emoji: '🍚',
    baseServings: 2,
    caloriesPerServing: 540,
    prepTimeMinutes: 26,
    ingredients: [
      RecipeIngredient(name: 'Sovány marhahús', amount: 280, unit: 'g'),
      RecipeIngredient(name: 'Főtt rizs', amount: 300, unit: 'g'),
      RecipeIngredient(name: 'Cukkini', amount: 240, unit: 'g'),
      RecipeIngredient(name: 'Paradicsompüré', amount: 50, unit: 'g'),
      RecipeIngredient(name: 'Fűszerkeverék', amount: 6, unit: 'g'),
    ],
    steps: [
      'A marhahúst pirítsd le, majd add hozzá a zöldségeket.',
      'Keverd hozzá a paradicsompürét, és főzd 3-4 percig sűrű raguvá.',
      'Add hozzá a főtt rizst, majd forgasd össze, amíg átmelegszik.',
    ],
    allergens: ['nincs kiemelt allergén'],
  ),
  Recipe(
    id: 'lentil_feta_dinner_plate',
    category: RecipeCategory.dinner,
    name: 'Meleg lencsés feta tányér',
    emoji: '🥗',
    baseServings: 2,
    caloriesPerServing: 445,
    prepTimeMinutes: 18,
    ingredients: [
      RecipeIngredient(name: 'Főtt lencse', amount: 360, unit: 'g'),
      RecipeIngredient(name: 'Feta sajt', amount: 90, unit: 'g'),
      RecipeIngredient(name: 'Spenót', amount: 90, unit: 'g'),
      RecipeIngredient(name: 'Paradicsom', amount: 160, unit: 'g'),
      RecipeIngredient(name: 'Olívaolaj', amount: 10, unit: 'ml'),
    ],
    steps: [
      'A zöldségeket vágd kockára.',
      'A zöldségeket pirítsd át.',
      'Keverd össze a lencsével és morzsolt fetával.',
      'Locsold meg olívaolajjal, majd hűtve vagy frissen tálald.',
    ],
    allergens: ['tejfehérje'],
  ),
  Recipe(
    id: 'chicken_noodle_soup_bowl',
    category: RecipeCategory.dinner,
    name: 'Csirkés rizstészta leveses tál',
    emoji: '🍜',
    baseServings: 2,
    caloriesPerServing: 465,
    prepTimeMinutes: 24,
    ingredients: [
      RecipeIngredient(name: 'Csirkemell', amount: 260, unit: 'g'),
      RecipeIngredient(name: 'Rizstészta', amount: 130, unit: 'g'),
      RecipeIngredient(name: 'Wok zöldség', amount: 260, unit: 'g'),
      RecipeIngredient(name: 'Szójaszósz', amount: 18, unit: 'ml'),
      RecipeIngredient(name: 'Citromlé', amount: 8, unit: 'ml'),
    ],
    steps: [
      'A csirkemellet süsd készre és szeleteld fel.',
      'A rizstésztát áztasd vagy főzd meg a csomagolás szerint.',
      'A zöldségeket pirítsd át.',
      'Kevés citromlével frissítsd, majd azonnal tálald.',
    ],
    allergens: ['szója'],
  ),
  Recipe(
    id: 'pork_couscous_evening',
    category: RecipeCategory.dinner,
    name: 'Sertésszűz kuszkusz salátával',
    emoji: '🍽️',
    baseServings: 2,
    caloriesPerServing: 530,
    prepTimeMinutes: 25,
    ingredients: [
      RecipeIngredient(name: 'Sertésszűz', amount: 280, unit: 'g'),
      RecipeIngredient(name: 'Kuszkusz', amount: 140, unit: 'g'),
      RecipeIngredient(name: 'Saláta mix', amount: 150, unit: 'g'),
      RecipeIngredient(name: 'Joghurtos öntet', amount: 60, unit: 'g'),
      RecipeIngredient(name: 'Mustár', amount: 12, unit: 'g'),
    ],
    steps: [
      'A sertésszüzet fűszerezd és süsd szeletekre.',
      'A kuszkuszt forró vízzel párold meg.',
      'A zöldségeket rendezd tálba.',
      'Keverj mustárt a joghurtos öntetbe, majd locsold a kuszkuszos salátára.',
    ],
    allergens: ['glutén', 'tejfehérje', 'mustár'],
  ),
  Recipe(
    id: 'chickpea_spinach_coconut_dinner',
    category: RecipeCategory.dinner,
    name: 'Spenótos kókuszos csicseriborsó',
    emoji: '🥘',
    isVegan: true,
    baseServings: 2,
    caloriesPerServing: 500,
    prepTimeMinutes: 23,
    ingredients: [
      RecipeIngredient(name: 'Csicseriborsó', amount: 380, unit: 'g'),
      RecipeIngredient(name: 'Kókusztej', amount: 220, unit: 'ml'),
      RecipeIngredient(name: 'Spenót', amount: 120, unit: 'g'),
      RecipeIngredient(name: 'Paradicsom', amount: 220, unit: 'g'),
      RecipeIngredient(name: 'Curry fűszer', amount: 8, unit: 'g'),
    ],
    steps: [
      'A csicseriborsót főzd össze paradicsommal, kókusztejjel és curryvel.',
      'Keverd össze spenóttal és paradicsommal.',
      'Főzd össze sűrű raguvá.',
      'Tálald a curry alapot rizzsel.',
    ],
    allergens: ['nincs kiemelt allergén'],
  ),
  Recipe(
    id: 'ham_egg_crispbread_dinner',
    category: RecipeCategory.dinner,
    name: 'Sonkás tojásos abonett tál',
    emoji: '🥚',
    baseServings: 1,
    caloriesPerServing: 410,
    prepTimeMinutes: 12,
    ingredients: [
      RecipeIngredient(name: 'Tojás', amount: 2, unit: 'db'),
      RecipeIngredient(name: 'Pulykasonka', amount: 70, unit: 'g'),
      RecipeIngredient(name: 'Teljes kiőrlésű abonett', amount: 35, unit: 'g'),
      RecipeIngredient(name: 'Cottage cheese', amount: 120, unit: 'g'),
      RecipeIngredient(name: 'Uborka', amount: 120, unit: 'g'),
    ],
    steps: [
      'A tojásokat főzd meg.',
      'A cottage cheese-t kanalazd tálba.',
      'A zöldségeket vágd fel.',
      'Tálald cottage cheese-zel, abonettel és tökmaggal.',
    ],
    allergens: ['tojás', 'tejfehérje', 'glutén'],
  ),
];

const snackRecipes = [
  Recipe(
    id: 'protein_yogurt_cup',
    category: RecipeCategory.snack,
    name: 'Protein joghurt pohár',
    emoji: '🍨',
    baseServings: 1,
    caloriesPerServing: 230,
    prepTimeMinutes: 4,
    ingredients: [
      RecipeIngredient(name: 'Görög joghurt', amount: 170, unit: 'g'),
      RecipeIngredient(name: 'Fehérjepor', amount: 15, unit: 'g'),
      RecipeIngredient(name: 'Eper', amount: 80, unit: 'g'),
      RecipeIngredient(name: 'Mandula', amount: 8, unit: 'g'),
    ],
    steps: [
      'Keverd össze a joghurtot a fehérjeporral.',
      'Tedd rá az epret és a mandulát.',
    ],
    allergens: ['tejfehérje', 'diófélék'],
  ),
  Recipe(
    id: 'apple_peanut_slices',
    category: RecipeCategory.snack,
    name: 'Almaszeletek mogyoróvajjal',
    emoji: '🍏',
    isVegan: true,
    baseServings: 1,
    caloriesPerServing: 210,
    prepTimeMinutes: 5,
    ingredients: [
      RecipeIngredient(name: 'Alma', amount: 180, unit: 'g'),
      RecipeIngredient(name: 'Mogyoróvaj', amount: 18, unit: 'g'),
      RecipeIngredient(name: 'Fahéj', amount: 1, unit: 'g'),
    ],
    steps: [
      'Az almát szeleteld fel.',
      'Kend meg vékonyan mogyoróvajjal és szórd meg fahéjjal.',
    ],
    allergens: ['földimogyoró'],
  ),
  Recipe(
    id: 'rice_cake_cottage',
    category: RecipeCategory.snack,
    name: 'Rizsszelet cottage cheese-zel',
    emoji: '🍘',
    baseServings: 1,
    caloriesPerServing: 190,
    prepTimeMinutes: 5,
    ingredients: [
      RecipeIngredient(name: 'Rizsszelet', amount: 2, unit: 'db'),
      RecipeIngredient(name: 'Cottage cheese', amount: 100, unit: 'g'),
      RecipeIngredient(name: 'Paradicsom', amount: 80, unit: 'g'),
      RecipeIngredient(name: 'Tökmag', amount: 6, unit: 'g'),
    ],
    steps: [
      'A rizsszeleteket kend meg cottage cheese-zel.',
      'Tedd rá a paradicsomot és szórd meg tökmaggal.',
    ],
    allergens: ['tejfehérje'],
  ),
  Recipe(
    id: 'banana_cocoa_bites',
    category: RecipeCategory.snack,
    name: 'Banános kakaós falatok',
    emoji: '🍌',
    isVegan: true,
    baseServings: 2,
    caloriesPerServing: 165,
    prepTimeMinutes: 10,
    ingredients: [
      RecipeIngredient(name: 'Banán', amount: 180, unit: 'g'),
      RecipeIngredient(name: 'Zabpehely', amount: 60, unit: 'g'),
      RecipeIngredient(name: 'Kakaópor', amount: 8, unit: 'g'),
      RecipeIngredient(name: 'Juharszirup', amount: 12, unit: 'g'),
    ],
    steps: [
      'A banánt törd össze.',
      'Keverd hozzá a zabot, kakaót és juharszirupot.',
      'Formázz falatokat és hűtsd 20 percig.',
    ],
    allergens: ['glutén'],
  ),
  Recipe(
    id: 'hummus_veggie_box',
    category: RecipeCategory.snack,
    name: 'Hummuszos zöldségdoboz',
    emoji: '🥕',
    isVegan: true,
    baseServings: 1,
    caloriesPerServing: 240,
    prepTimeMinutes: 7,
    ingredients: [
      RecipeIngredient(name: 'Hummusz', amount: 80, unit: 'g'),
      RecipeIngredient(name: 'Répa', amount: 100, unit: 'g'),
      RecipeIngredient(name: 'Uborka', amount: 100, unit: 'g'),
      RecipeIngredient(name: 'Paprika', amount: 80, unit: 'g'),
    ],
    steps: ['A zöldségeket vágd hasábokra.', 'Tedd dobozba hummusszal együtt.'],
    allergens: ['szezám'],
  ),
  Recipe(
    id: 'protein_pudding',
    category: RecipeCategory.snack,
    name: 'Fehérjés puding',
    emoji: '🍮',
    baseServings: 1,
    caloriesPerServing: 260,
    prepTimeMinutes: 6,
    ingredients: [
      RecipeIngredient(name: 'Skyr vagy görög joghurt', amount: 200, unit: 'g'),
      RecipeIngredient(name: 'Fehérjepor', amount: 20, unit: 'g'),
      RecipeIngredient(name: 'Kakaópor', amount: 6, unit: 'g'),
      RecipeIngredient(name: 'Bogyós gyümölcs', amount: 60, unit: 'g'),
    ],
    steps: [
      'Keverd simára a joghurtot fehérjeporral és kakaóval.',
      'Tálald gyümölccsel.',
    ],
    allergens: ['tejfehérje'],
  ),
  Recipe(
    id: 'egg_avocado_snack',
    category: RecipeCategory.snack,
    name: 'Főtt tojás avokádóval',
    emoji: '🥚',
    baseServings: 1,
    caloriesPerServing: 255,
    prepTimeMinutes: 10,
    ingredients: [
      RecipeIngredient(name: 'Tojás', amount: 2, unit: 'db'),
      RecipeIngredient(name: 'Avokádó', amount: 60, unit: 'g'),
      RecipeIngredient(name: 'Citromlé', amount: 5, unit: 'ml'),
      RecipeIngredient(name: 'Só, bors', amount: 1, unit: 'csipet'),
    ],
    steps: [
      'A tojásokat főzd meg.',
      'Az avokádót szeleteld mellé, citromlével ízesítsd.',
    ],
    allergens: ['tojás'],
  ),
  Recipe(
    id: 'tuna_crackers',
    category: RecipeCategory.snack,
    name: 'Tonhalas ropogós falatok',
    emoji: '🐟',
    baseServings: 1,
    caloriesPerServing: 285,
    prepTimeMinutes: 7,
    ingredients: [
      RecipeIngredient(name: 'Tonhal', amount: 90, unit: 'g'),
      RecipeIngredient(name: 'Teljes kiőrlésű keksz', amount: 35, unit: 'g'),
      RecipeIngredient(name: 'Görög joghurt', amount: 35, unit: 'g'),
      RecipeIngredient(name: 'Uborka', amount: 60, unit: 'g'),
    ],
    steps: [
      'A tonhalat keverd össze joghurttal.',
      'Kanalazd kekszekre, uborkával tálald.',
    ],
    allergens: ['hal', 'glutén', 'tejfehérje'],
  ),
  Recipe(
    id: 'cottage_berry_bowl',
    category: RecipeCategory.snack,
    name: 'Túrós bogyós tál',
    emoji: '🫐',
    baseServings: 1,
    caloriesPerServing: 220,
    prepTimeMinutes: 5,
    ingredients: [
      RecipeIngredient(name: 'Túró', amount: 150, unit: 'g'),
      RecipeIngredient(name: 'Bogyós gyümölcs', amount: 90, unit: 'g'),
      RecipeIngredient(name: 'Méz', amount: 8, unit: 'g'),
      RecipeIngredient(name: 'Darált dió', amount: 8, unit: 'g'),
    ],
    steps: ['A túrót keverd krémesre.', 'Tedd rá a gyümölcsöt, mézet és diót.'],
    allergens: ['tejfehérje', 'diófélék'],
  ),
  Recipe(
    id: 'mini_chicken_wrap',
    category: RecipeCategory.snack,
    name: 'Mini csirkés wrap',
    emoji: '🌯',
    baseServings: 1,
    caloriesPerServing: 310,
    prepTimeMinutes: 10,
    ingredients: [
      RecipeIngredient(name: 'Mini tortilla', amount: 45, unit: 'g'),
      RecipeIngredient(name: 'Sült csirkemell', amount: 70, unit: 'g'),
      RecipeIngredient(name: 'Joghurtos szósz', amount: 25, unit: 'g'),
      RecipeIngredient(name: 'Saláta', amount: 40, unit: 'g'),
    ],
    steps: [
      'A tortillát kend meg joghurtos szósszal.',
      'Töltsd meg csirkével és salátával.',
      'Tekerd fel és vágd félbe.',
    ],
    allergens: ['glutén', 'tejfehérje'],
  ),
  Recipe(
    id: 'date_free_cocoa_yogurt',
    category: RecipeCategory.snack,
    name: 'Kakaós skyr ropogóssal',
    emoji: '🍫',
    baseServings: 1,
    caloriesPerServing: 275,
    prepTimeMinutes: 5,
    ingredients: [
      RecipeIngredient(name: 'Skyr vagy görög joghurt', amount: 190, unit: 'g'),
      RecipeIngredient(name: 'Kakaópor', amount: 7, unit: 'g'),
      RecipeIngredient(name: 'Juharszirup', amount: 8, unit: 'g'),
      RecipeIngredient(name: 'Mandula', amount: 10, unit: 'g'),
    ],
    steps: [
      'Keverd simára a joghurtot fehérjeporral és kakaóval.',
      'Tálald gyümölccsel.',
    ],
    allergens: ['tejfehérje', 'diófélék'],
  ),
  Recipe(
    id: 'hummus_rice_cake_stack',
    category: RecipeCategory.snack,
    name: 'Hummuszos rizsszelet torony',
    emoji: '🍘',
    isVegan: true,
    baseServings: 1,
    caloriesPerServing: 245,
    prepTimeMinutes: 6,
    ingredients: [
      RecipeIngredient(name: 'Rizsszelet', amount: 3, unit: 'db'),
      RecipeIngredient(name: 'Hummusz', amount: 70, unit: 'g'),
      RecipeIngredient(name: 'Uborka', amount: 80, unit: 'g'),
      RecipeIngredient(name: 'Paprika', amount: 60, unit: 'g'),
    ],
    steps: [
      'A zöldségeket vágd hasábokra.',
      'A rizsszeleteket kend meg hummusszal.',
      'Tedd dobozba hummusszal együtt.',
    ],
    allergens: ['szezám'],
  ),
  Recipe(
    id: 'salmon_cucumber_bites',
    category: RecipeCategory.snack,
    name: 'Lazacos uborkás falatok',
    emoji: '🥒',
    baseServings: 1,
    caloriesPerServing: 260,
    prepTimeMinutes: 8,
    ingredients: [
      RecipeIngredient(name: 'Füstölt lazac', amount: 70, unit: 'g'),
      RecipeIngredient(name: 'Uborka', amount: 140, unit: 'g'),
      RecipeIngredient(name: 'Krémsajt', amount: 35, unit: 'g'),
      RecipeIngredient(name: 'Citromlé', amount: 5, unit: 'ml'),
    ],
    steps: [
      'A zöldségeket vágd fel.',
      'Kend meg krémsajttal, majd tedd rá a lazacot és uborkát.',
      'Kevés citromlével frissítsd, majd azonnal tálald.',
    ],
    allergens: ['hal', 'tejfehérje'],
  ),
  Recipe(
    id: 'chickpea_crunch_box',
    category: RecipeCategory.snack,
    name: 'Csicseriborsós ropogós doboz',
    emoji: '🧆',
    isVegan: true,
    baseServings: 1,
    caloriesPerServing: 300,
    prepTimeMinutes: 14,
    ingredients: [
      RecipeIngredient(name: 'Csicseriborsó', amount: 170, unit: 'g'),
      RecipeIngredient(name: 'Fűszerkeverék', amount: 5, unit: 'g'),
      RecipeIngredient(name: 'Répa', amount: 90, unit: 'g'),
      RecipeIngredient(name: 'Hummusz', amount: 45, unit: 'g'),
    ],
    steps: [
      'A zöldségeket vágd hasábokra.',
      'A csicseriborsót forgasd össze a fűszerkeverékkel, majd pirítsd át 6-8 perc alatt.',
      'Tedd dobozba hummusszal együtt.',
    ],
    allergens: ['szezám'],
  ),
  Recipe(
    id: 'turkey_cheese_rolls',
    category: RecipeCategory.snack,
    name: 'Pulykás sajtos tekercsek',
    emoji: '🧀',
    baseServings: 1,
    caloriesPerServing: 360,
    prepTimeMinutes: 7,
    ingredients: [
      RecipeIngredient(name: 'Pulykamell sonka', amount: 90, unit: 'g'),
      RecipeIngredient(name: 'Mini tortilla', amount: 45, unit: 'g'),
      RecipeIngredient(name: 'Light sajt', amount: 35, unit: 'g'),
      RecipeIngredient(name: 'Saláta', amount: 45, unit: 'g'),
      RecipeIngredient(name: 'Paprika', amount: 60, unit: 'g'),
    ],
    steps: [
      'A zöldségeket vágd fel.',
      'Melegítsd át a tortillát, majd tedd rá a sonkát, sajtot és zöldséget.',
      'Tekerd fel és vágd félbe.',
    ],
    allergens: ['glutén', 'tejfehérje'],
  ),
  Recipe(
    id: 'quinoa_berry_snack_cup',
    category: RecipeCategory.snack,
    name: 'Quinoás bogyós snack pohár',
    emoji: '🫐',
    baseServings: 1,
    caloriesPerServing: 265,
    prepTimeMinutes: 12,
    ingredients: [
      RecipeIngredient(name: 'Quinoa', amount: 40, unit: 'g'),
      RecipeIngredient(name: 'Bogyós gyümölcs', amount: 90, unit: 'g'),
      RecipeIngredient(name: 'Görög joghurt', amount: 120, unit: 'g'),
      RecipeIngredient(name: 'Méz', amount: 6, unit: 'g'),
    ],
    steps: [
      'A quinoát főzd meg.',
      'A joghurtot kanalazd pohárba vagy tálba.',
      'Tálald bogyós gyümölccsel.',
    ],
    allergens: ['tejfehérje'],
  ),
  Recipe(
    id: 'avocado_tuna_egg_boat',
    category: RecipeCategory.snack,
    name: 'Avokádós tonhalas tojásfalat',
    emoji: '🥑',
    baseServings: 1,
    caloriesPerServing: 330,
    prepTimeMinutes: 10,
    ingredients: [
      RecipeIngredient(name: 'Avokádó', amount: 70, unit: 'g'),
      RecipeIngredient(name: 'Tonhal', amount: 70, unit: 'g'),
      RecipeIngredient(name: 'Tojás', amount: 1, unit: 'db'),
      RecipeIngredient(name: 'Citromlé', amount: 5, unit: 'ml'),
    ],
    steps: [
      'A tojásokat főzd meg.',
      'A tonhalat keverd össze citromlével, sóval és borssal.',
      'Az avokádót szeleteld mellé, citromlével ízesítsd.',
    ],
    allergens: ['hal', 'tojás'],
  ),
  Recipe(
    id: 'warm_banana_oat_bites',
    category: RecipeCategory.snack,
    name: 'Meleg banános zabfalatok',
    emoji: '🍌',
    isVegan: true,
    baseServings: 2,
    caloriesPerServing: 190,
    prepTimeMinutes: 18,
    ingredients: [
      RecipeIngredient(name: 'Banán', amount: 180, unit: 'g'),
      RecipeIngredient(name: 'Zabpehely', amount: 70, unit: 'g'),
      RecipeIngredient(name: 'Kakaópor', amount: 7, unit: 'g'),
      RecipeIngredient(name: 'Mogyoróvaj', amount: 18, unit: 'g'),
    ],
    steps: [
      'A banánt törd össze.',
      'Keverd hozzá a zabot, kakaót és mogyoróvajat.',
      'Formázz falatokat és hűtsd 20 percig.',
    ],
    allergens: ['glutén', 'földimogyoró'],
  ),
  Recipe(
    id: 'feta_tomato_crispbread',
    category: RecipeCategory.snack,
    name: 'Fetás paradicsomos abonett',
    emoji: '🍅',
    baseServings: 1,
    caloriesPerServing: 250,
    prepTimeMinutes: 6,
    ingredients: [
      RecipeIngredient(name: 'Teljes kiőrlésű abonett', amount: 35, unit: 'g'),
      RecipeIngredient(name: 'Feta sajt', amount: 55, unit: 'g'),
      RecipeIngredient(name: 'Paradicsom', amount: 110, unit: 'g'),
      RecipeIngredient(name: 'Tökmag', amount: 6, unit: 'g'),
    ],
    steps: [
      'A zöldségeket vágd fel.',
      'Tedd rá a paradicsomot és szórd meg tökmaggal.',
      'Locsold meg olívaolajjal, majd hűtve vagy frissen tálald.',
    ],
    allergens: ['glutén', 'tejfehérje'],
  ),
  Recipe(
    id: 'mini_potato_tzatziki_box',
    category: RecipeCategory.snack,
    name: 'Mini burgonyás tzatziki doboz',
    emoji: '🥔',
    baseServings: 1,
    caloriesPerServing: 295,
    prepTimeMinutes: 18,
    ingredients: [
      RecipeIngredient(name: 'Burgonya', amount: 180, unit: 'g'),
      RecipeIngredient(name: 'Tzatziki', amount: 80, unit: 'g'),
      RecipeIngredient(name: 'Uborka', amount: 90, unit: 'g'),
      RecipeIngredient(name: 'Pulykasonka', amount: 50, unit: 'g'),
    ],
    steps: [
      'A burgonyát főzd vagy süsd puhára.',
      'A zöldségeket vágd fel.',
      'Keverd össze a burgonyát a tzatzikivel, majd tálald uborkával és pulykasonkával.',
    ],
    allergens: ['tejfehérje'],
  ),
];

const allRecipes = [
  ...breakfastRecipes,
  ...lunchRecipes,
  ...dinnerRecipes,
  ...snackRecipes,
];

Recipe? recipeById(String id) {
  for (final recipe in allRecipes) {
    if (recipe.id == id) return recipe;
  }
  return null;
}
